# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class AccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :admin_name, T::String
    attribute :edition, T::String
    attribute :email, T::String
    attribute :grace_period_in_days, T::Float
    attribute :name, T::String
    attribute? :admin_password, T::String.optional
    attribute? :admin_rsa_public_key, T::String.optional
    attribute? :admin_user_type, T::String.optional
    attribute? :comment, T::String.optional
    attribute? :first_name, T::String.optional
    attribute? :is_org_admin, T::String.optional
    attribute? :last_name, T::String.optional
    attribute? :must_change_password, T::String.optional
    attribute? :region, T::String.optional
    attribute? :region_group, T::String.optional
  end
end
