# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_authentication_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeAuthenticationPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_authentication_policy,
      attributes_class: Snowflake::Types::AuthenticationPolicyAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema],
      map_present: [:authentication_methods, :client_types, :comment, :mfa_authentication_methods, :mfa_enrollment, :security_integrations]
  end
  module Snowflake
    include SnowflakeAuthenticationPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
