# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class AuthenticationPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute? :authentication_methods, T::Array.of(T::String).optional
    attribute? :client_types, T::Array.of(T::String).optional
    attribute? :comment, T::String.optional
    attribute? :mfa_authentication_methods, T::Array.of(T::String).optional
    attribute? :mfa_enrollment, T::String.optional
    attribute? :security_integrations, T::Array.of(T::String).optional
  end
end
