# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_procedure_javascript/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeProcedureJavascript
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_procedure_javascript,
      attributes_class: Snowflake::Types::ProcedureJavascriptAttributes,
      outputs: { id: :id },
      map: [:database, :name, :procedure_definition, :return_type, :schema],
      map_present: [:arguments, :comment, :execute_as, :is_secure, :null_input_behavior]
  end
  module Snowflake
    include SnowflakeProcedureJavascript
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
