# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_external_table/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeExternalTable
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_external_table,
      attributes_class: Snowflake::Types::ExternalTableAttributes,
      outputs: { id: :id },
      map: [:column, :database, :file_format, :location, :name, :schema],
      map_present: [:aws_sns_topic, :comment, :partition_by, :pattern, :table_format, :tag],
      map_bool: [:auto_refresh, :copy_grants, :refresh_on_create]
  end
  module Snowflake
    include SnowflakeExternalTable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
