# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class GrantDatabaseRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database_role_name, T::String
    attribute? :parent_database_role_name, T::String.optional
    attribute? :parent_role_name, T::String.optional
    attribute? :share_name, T::String.optional
  end
end
