# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class MaterializedViewAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute :statement, T::String
    attribute :warehouse, T::String
    attribute? :comment, T::String.optional
    attribute? :is_secure, T::Bool.optional
    attribute? :or_replace, T::Bool.optional
    attribute? :tag, T::Array.of(T::Hash).optional
  end
end
