# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_procedure_python/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeProcedurePython
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_procedure_python,
      attributes_class: Snowflake::Types::ProcedurePythonAttributes,
      outputs: { id: :id },
      map: [:database, :handler, :name, :return_type, :runtime_version, :schema, :snowpark_package],
      map_present: [:arguments, :comment, :execute_as, :external_access_integrations, :imports, :is_secure, :null_input_behavior, :packages, :procedure_definition, :secrets]
  end
  module Snowflake
    include SnowflakeProcedurePython
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
