# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_failover_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeFailoverGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_failover_group,
      attributes_class: Snowflake::Types::FailoverGroupAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:allowed_accounts, :allowed_databases, :allowed_integration_types, :allowed_shares, :from_replica, :object_types, :replication_schedule],
      map_bool: [:ignore_edition_check]
  end
  module Snowflake
    include SnowflakeFailoverGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
