# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class FailoverGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :name, T::String
    attribute? :allowed_accounts, T::Array.of(T::String).optional
    attribute? :allowed_databases, T::Array.of(T::String).optional
    attribute? :allowed_integration_types, T::Array.of(T::String).optional
    attribute? :allowed_shares, T::Array.of(T::String).optional
    attribute? :from_replica, T::Array.of(T::Hash).optional
    attribute? :ignore_edition_check, T::Bool.optional
    attribute? :object_types, T::Array.of(T::String).optional
    attribute? :replication_schedule, T::Array.of(T::Hash).optional
  end
end
