# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_secret_with_basic_authentication/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSecretWithBasicAuthentication
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_secret_with_basic_authentication,
      attributes_class: Snowflake::Types::SecretWithBasicAuthenticationAttributes,
      outputs: { id: :id },
      map: [:database, :name, :password, :schema, :username],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeSecretWithBasicAuthentication
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
