# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_file_format/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeFileFormat
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_file_format,
      attributes_class: Snowflake::Types::FileFormatAttributes,
      outputs: { id: :id },
      map: [:database, :format_type, :name, :schema],
      map_present: [:comment, :file_extension, :skip_header],
      map_bool: [:allow_duplicate, :binary_as_text, :disable_auto_convert, :disable_snowflake_data, :empty_field_as_null, :enable_octal, :error_on_column_count_mismatch, :ignore_utf8_errors, :parse_header, :preserve_space, :replace_invalid_characters, :skip_blank_lines, :skip_byte_order_mark, :strip_null_values, :strip_outer_array, :strip_outer_element, :trim_space]
  end
  module Snowflake
    include SnowflakeFileFormat
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
