# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_api_authentication_integration_with_authorization_code_grant/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeApiAuthenticationIntegrationWithAuthorizationCodeGrant
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_api_authentication_integration_with_authorization_code_grant,
      attributes_class: Snowflake::Types::ApiAuthenticationIntegrationWithAuthorizationCodeGrantAttributes,
      outputs: { id: :id },
      map: [:name, :oauth_client_id, :oauth_client_secret],
      map_present: [:comment, :oauth_access_token_validity, :oauth_allowed_scopes, :oauth_authorization_endpoint, :oauth_client_auth_method, :oauth_refresh_token_validity, :oauth_token_endpoint],
      map_bool: [:enabled]
  end
  module Snowflake
    include SnowflakeApiAuthenticationIntegrationWithAuthorizationCodeGrant
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
