# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_external_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeExternalVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_external_volume,
      attributes_class: Snowflake::Types::ExternalVolumeAttributes,
      outputs: { id: :id },
      map: [:name, :storage_location],
      map_present: [:allow_writes, :comment]
  end
  module Snowflake
    include SnowflakeExternalVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
