# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ExternalVolumeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :name, T::String
    attribute :storage_location, T::Array.of(T::Hash)
    attribute? :allow_writes, T::String.optional
    attribute? :comment, T::String.optional
  end
end
