# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_saml2_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSaml2Integration
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_saml2_integration,
      attributes_class: Snowflake::Types::Saml2IntegrationAttributes,
      outputs: { id: :id },
      map: [:name, :saml2_issuer, :saml2_provider, :saml2_sso_url, :saml2_x509_cert],
      map_present: [:allowed_email_patterns, :allowed_user_domains, :comment, :enabled, :saml2_enable_sp_initiated, :saml2_force_authn, :saml2_post_logout_redirect_url, :saml2_requested_nameid_format, :saml2_sign_request, :saml2_snowflake_acs_url, :saml2_snowflake_issuer_url, :saml2_sp_initiated_login_page_label]
  end
  module Snowflake
    include SnowflakeSaml2Integration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
