# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ProcedureJavaAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :handler, T::String
    attribute :name, T::String
    attribute :return_type, T::String
    attribute :runtime_version, T::String
    attribute :schema, T::String
    attribute :snowpark_package, T::String
    attribute? :arguments, T::Array.of(T::Hash).optional
    attribute? :comment, T::String.optional
    attribute? :execute_as, T::String.optional
    attribute? :external_access_integrations, T::Array.of(T::String).optional
    attribute? :imports, T::Array.of(T::Hash).optional
    attribute? :is_secure, T::String.optional
    attribute? :null_input_behavior, T::String.optional
    attribute? :packages, T::Array.of(T::String).optional
    attribute? :procedure_definition, T::String.optional
    attribute? :secrets, T::Array.of(T::Hash).optional
    attribute? :target_path, T::Array.of(T::Hash).optional
  end
end
