# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_grant_ownership/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeGrantOwnership
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_grant_ownership,
      attributes_class: Snowflake::Types::GrantOwnershipAttributes,
      outputs: { id: :id },
      map: [:on],
      map_present: [:account_role_name, :database_role_name, :outbound_privileges]
  end
  module Snowflake
    include SnowflakeGrantOwnership
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
