# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class GrantOwnershipAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :on, T::Array.of(T::Hash)
    attribute? :account_role_name, T::String.optional
    attribute? :database_role_name, T::String.optional
    attribute? :outbound_privileges, T::String.optional
  end
end
