# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_function_sql/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeFunctionSql
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_function_sql,
      attributes_class: Snowflake::Types::FunctionSqlAttributes,
      outputs: { id: :id },
      map: [:database, :function_definition, :name, :return_type, :schema],
      map_present: [:arguments, :comment, :is_secure, :return_results_behavior]
  end
  module Snowflake
    include SnowflakeFunctionSql
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
