# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_table/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeTable
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_table,
      attributes_class: Snowflake::Types::TableAttributes,
      outputs: { id: :id },
      map: [:column, :database, :name, :schema],
      map_present: [:cluster_by, :comment, :data_retention_time_in_days, :primary_key, :tag],
      map_bool: [:change_tracking]
  end
  module Snowflake
    include SnowflakeTable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
