# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_account_parameter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeAccountParameter
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_account_parameter,
      attributes_class: Snowflake::Types::AccountParameterAttributes,
      outputs: { id: :id },
      map: [:key, :value]
  end
  module Snowflake
    include SnowflakeAccountParameter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
