# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_network_policy_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeNetworkPolicyAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_network_policy_attachment,
      attributes_class: Snowflake::Types::NetworkPolicyAttachmentAttributes,
      outputs: { id: :id },
      map: [:network_policy_name],
      map_present: [:users],
      map_bool: [:set_for_account]
  end
  module Snowflake
    include SnowflakeNetworkPolicyAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
