# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class NetworkPolicyAttachmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :network_policy_name, T::String
    attribute? :set_for_account, T::Bool.optional
    attribute? :users, T::Array.of(T::String).optional
  end
end
