# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_secret_with_generic_string/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSecretWithGenericString
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_secret_with_generic_string,
      attributes_class: Snowflake::Types::SecretWithGenericStringAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema, :secret_string],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeSecretWithGenericString
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
