# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_grant_privileges_to_database_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeGrantPrivilegesToDatabaseRole
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_grant_privileges_to_database_role,
      attributes_class: Snowflake::Types::GrantPrivilegesToDatabaseRoleAttributes,
      outputs: { id: :id },
      map: [:database_role_name],
      map_present: [:always_apply_trigger, :on_database, :on_schema, :on_schema_object, :privileges],
      map_bool: [:all_privileges, :always_apply, :with_grant_option]
  end
  module Snowflake
    include SnowflakeGrantPrivilegesToDatabaseRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
