# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ManagedAccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :admin_name, T::String
    attribute :admin_password, T::String
    attribute :name, T::String
    attribute? :comment, T::String.optional
    attribute? :type, T::String.optional
  end
end
