# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_email_notification_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeEmailNotificationIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_email_notification_integration,
      attributes_class: Snowflake::Types::EmailNotificationIntegrationAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:allowed_recipients, :comment],
      map_bool: [:enabled]
  end
  module Snowflake
    include SnowflakeEmailNotificationIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
