# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_view/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeView
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_view,
      attributes_class: Snowflake::Types::ViewAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema, :statement],
      map_present: [:aggregation_policy, :change_tracking, :column, :comment, :data_metric_function, :data_metric_schedule, :is_recursive, :is_secure, :is_temporary, :row_access_policy],
      map_bool: [:copy_grants]
  end
  module Snowflake
    include SnowflakeView
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
