# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ViewAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute :statement, T::String
    attribute? :aggregation_policy, T::Array.of(T::Hash).optional
    attribute? :change_tracking, T::String.optional
    attribute? :column, T::Array.of(T::Hash).optional
    attribute? :comment, T::String.optional
    attribute? :copy_grants, T::Bool.optional
    attribute? :data_metric_function, T::Array.of(T::Hash).optional
    attribute? :data_metric_schedule, T::Array.of(T::Hash).optional
    attribute? :is_recursive, T::String.optional
    attribute? :is_secure, T::String.optional
    attribute? :is_temporary, T::String.optional
    attribute? :row_access_policy, T::Array.of(T::Hash).optional
  end
end
