# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_network_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeNetworkRule
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_network_rule,
      attributes_class: Snowflake::Types::NetworkRuleAttributes,
      outputs: { id: :id },
      map: [:database, :mode, :name, :schema, :type, :value_list],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeNetworkRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
