# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class NetworkRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :mode, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute :type, T::String
    attribute :value_list, T::Array.of(T::String)
    attribute? :comment, T::String.optional
  end
end
