# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_sequence/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSequence
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_sequence,
      attributes_class: Snowflake::Types::SequenceAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema],
      map_present: [:comment, :increment, :ordering]
  end
  module Snowflake
    include SnowflakeSequence
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
