# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_database/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeDatabase
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_database,
      attributes_class: Snowflake::Types::DatabaseAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:comment, :replication],
      map_bool: [:drop_public_schema_on_creation, :is_transient]
  end
  module Snowflake
    include SnowflakeDatabase
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
