# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class DatabaseAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :name, T::String
    attribute? :comment, T::String.optional
    attribute? :drop_public_schema_on_creation, T::Bool.optional
    attribute? :is_transient, T::Bool.optional
    attribute? :replication, T::Array.of(T::Hash).optional
  end
end
