# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_object_parameter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeObjectParameter
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_object_parameter,
      attributes_class: Snowflake::Types::ObjectParameterAttributes,
      outputs: { id: :id },
      map: [:key, :value],
      map_present: [:object_identifier, :object_type],
      map_bool: [:on_account]
  end
  module Snowflake
    include SnowflakeObjectParameter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
