# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class GrantPrivilegesToAccountRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :account_role_name, T::String
    attribute? :all_privileges, T::Bool.optional
    attribute? :always_apply, T::Bool.optional
    attribute? :always_apply_trigger, T::String.optional
    attribute? :on_account, T::Bool.optional
    attribute? :on_account_object, T::Array.of(T::Hash).optional
    attribute? :on_schema, T::Array.of(T::Hash).optional
    attribute? :on_schema_object, T::Array.of(T::Hash).optional
    attribute? :privileges, T::Array.of(T::String).optional
    attribute? :with_grant_option, T::Bool.optional
  end
end
