# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_schema/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSchema
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_schema,
      attributes_class: Snowflake::Types::SchemaAttributes,
      outputs: { id: :id },
      map: [:database, :name],
      map_present: [:comment, :is_transient, :with_managed_access]
  end
  module Snowflake
    include SnowflakeSchema
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
