# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class SchemaAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :name, T::String
    attribute? :comment, T::String.optional
    attribute? :is_transient, T::String.optional
    attribute? :with_managed_access, T::String.optional
  end
end
