# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_scim_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeScimIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_scim_integration,
      attributes_class: Snowflake::Types::ScimIntegrationAttributes,
      outputs: { id: :id },
      map: [:name, :run_as_role, :scim_client],
      map_present: [:comment, :network_policy, :sync_password],
      map_bool: [:enabled]
  end
  module Snowflake
    include SnowflakeScimIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
