# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ScimIntegrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :enabled, T::Bool
    attribute :name, T::String
    attribute :run_as_role, T::String
    attribute :scim_client, T::String
    attribute? :comment, T::String.optional
    attribute? :network_policy, T::String.optional
    attribute? :sync_password, T::String.optional
  end
end
