# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_masking_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeMaskingPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_masking_policy,
      attributes_class: Snowflake::Types::MaskingPolicyAttributes,
      outputs: { id: :id },
      map: [:argument, :body, :database, :name, :return_data_type, :schema],
      map_present: [:comment, :exempt_other_policies]
  end
  module Snowflake
    include SnowflakeMaskingPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
