# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class MaskingPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :argument, T::Array.of(T::Hash)
    attribute :body, T::String
    attribute :database, T::String
    attribute :name, T::String
    attribute :return_data_type, T::String
    attribute :schema, T::String
    attribute? :comment, T::String.optional
    attribute? :exempt_other_policies, T::String.optional
  end
end
