# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_function_python/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeFunctionPython
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_function_python,
      attributes_class: Snowflake::Types::FunctionPythonAttributes,
      outputs: { id: :id },
      map: [:database, :handler, :name, :return_type, :runtime_version, :schema],
      map_present: [:arguments, :comment, :external_access_integrations, :function_definition, :imports, :is_aggregate, :is_secure, :null_input_behavior, :packages, :return_results_behavior, :secrets]
  end
  module Snowflake
    include SnowflakeFunctionPython
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
