# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_user_authentication_policy_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeUserAuthenticationPolicyAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_user_authentication_policy_attachment,
      attributes_class: Snowflake::Types::UserAuthenticationPolicyAttachmentAttributes,
      outputs: { id: :id },
      map: [:authentication_policy_name, :user_name]
  end
  module Snowflake
    include SnowflakeUserAuthenticationPolicyAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
