# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_warehouse/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeWarehouse
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_warehouse,
      attributes_class: Snowflake::Types::WarehouseAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:auto_resume, :auto_suspend, :comment, :enable_query_acceleration, :max_cluster_count, :min_cluster_count, :query_acceleration_max_scale_factor, :resource_monitor, :scaling_policy, :warehouse_size, :warehouse_type],
      map_bool: [:initially_suspended]
  end
  module Snowflake
    include SnowflakeWarehouse
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
