# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class WarehouseAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :name, T::String
    attribute? :auto_resume, T::String.optional
    attribute? :auto_suspend, T::Float.optional
    attribute? :comment, T::String.optional
    attribute? :enable_query_acceleration, T::String.optional
    attribute? :initially_suspended, T::Bool.optional
    attribute? :max_cluster_count, T::Float.optional
    attribute? :min_cluster_count, T::Float.optional
    attribute? :query_acceleration_max_scale_factor, T::Float.optional
    attribute? :resource_monitor, T::String.optional
    attribute? :scaling_policy, T::String.optional
    attribute? :warehouse_size, T::String.optional
    attribute? :warehouse_type, T::String.optional
  end
end
