# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_service_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeServiceUser
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_service_user,
      attributes_class: Snowflake::Types::ServiceUserAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:comment, :days_to_expiry, :default_namespace, :default_role, :default_secondary_roles_option, :default_warehouse, :disabled, :display_name, :email, :login_name, :mins_to_unlock, :rsa_public_key, :rsa_public_key_2]
  end
  module Snowflake
    include SnowflakeServiceUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
