# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ServiceUserAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :name, T::String
    attribute? :comment, T::String.optional
    attribute? :days_to_expiry, T::Float.optional
    attribute? :default_namespace, T::String.optional
    attribute? :default_role, T::String.optional
    attribute? :default_secondary_roles_option, T::String.optional
    attribute? :default_warehouse, T::String.optional
    attribute? :disabled, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :email, T::String.optional
    attribute? :login_name, T::String.optional
    attribute? :mins_to_unlock, T::Float.optional
    attribute? :rsa_public_key, T::String.optional
    attribute? :rsa_public_key_2, T::String.optional
  end
end
