# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_share/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeShare
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_share,
      attributes_class: Snowflake::Types::ShareAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:accounts, :comment]
  end
  module Snowflake
    include SnowflakeShare
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
