# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_dynamic_table/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeDynamicTable
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_dynamic_table,
      attributes_class: Snowflake::Types::DynamicTableAttributes,
      outputs: { id: :id },
      map: [:database, :name, :query, :schema, :target_lag, :warehouse],
      map_present: [:comment, :initialize, :refresh_mode],
      map_bool: [:or_replace]
  end
  module Snowflake
    include SnowflakeDynamicTable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
