# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_row_access_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeRowAccessPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_row_access_policy,
      attributes_class: Snowflake::Types::RowAccessPolicyAttributes,
      outputs: { id: :id },
      map: [:argument, :body, :database, :name, :schema],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeRowAccessPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
