# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class GrantPrivilegesToShareAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :privileges, T::Array.of(T::String)
    attribute :to_share, T::String
    attribute? :on_all_tables_in_schema, T::String.optional
    attribute? :on_database, T::String.optional
    attribute? :on_function, T::String.optional
    attribute? :on_schema, T::String.optional
    attribute? :on_table, T::String.optional
    attribute? :on_tag, T::String.optional
    attribute? :on_view, T::String.optional
  end
end
