# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_function_scala/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeFunctionScala
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_function_scala,
      attributes_class: Snowflake::Types::FunctionScalaAttributes,
      outputs: { id: :id },
      map: [:database, :handler, :name, :return_type, :runtime_version, :schema],
      map_present: [:arguments, :comment, :external_access_integrations, :function_definition, :imports, :is_secure, :null_input_behavior, :packages, :return_results_behavior, :secrets, :target_path]
  end
  module Snowflake
    include SnowflakeFunctionScala
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
