# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_account_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeAccountRole
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_account_role,
      attributes_class: Snowflake::Types::AccountRoleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeAccountRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
