# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_execute/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeExecute
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_execute,
      attributes_class: Snowflake::Types::ExecuteAttributes,
      outputs: { id: :id },
      map: [:execute, :revert],
      map_present: [:query]
  end
  module Snowflake
    include SnowflakeExecute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
