# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_cortex_search_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeCortexSearchService
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_cortex_search_service,
      attributes_class: Snowflake::Types::CortexSearchServiceAttributes,
      outputs: { id: :id },
      map: [:database, :name, :on, :query, :schema, :target_lag, :warehouse],
      map_present: [:attributes, :comment]
  end
  module Snowflake
    include SnowflakeCortexSearchService
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
