# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_external_oauth_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeExternalOauthIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_external_oauth_integration,
      attributes_class: Snowflake::Types::ExternalOauthIntegrationAttributes,
      outputs: { id: :id },
      map: [:external_oauth_issuer, :external_oauth_snowflake_user_mapping_attribute, :external_oauth_token_user_mapping_claim, :external_oauth_type, :name],
      map_present: [:comment, :external_oauth_allowed_roles_list, :external_oauth_any_role_mode, :external_oauth_audience_list, :external_oauth_blocked_roles_list, :external_oauth_jws_keys_url, :external_oauth_rsa_public_key, :external_oauth_rsa_public_key_2, :external_oauth_scope_delimiter, :external_oauth_scope_mapping_attribute],
      map_bool: [:enabled]
  end
  module Snowflake
    include SnowflakeExternalOauthIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
