# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ExternalOauthIntegrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :enabled, T::Bool
    attribute :external_oauth_issuer, T::String
    attribute :external_oauth_snowflake_user_mapping_attribute, T::String
    attribute :external_oauth_token_user_mapping_claim, T::Array.of(T::String)
    attribute :external_oauth_type, T::String
    attribute :name, T::String
    attribute? :comment, T::String.optional
    attribute? :external_oauth_allowed_roles_list, T::Array.of(T::String).optional
    attribute? :external_oauth_any_role_mode, T::String.optional
    attribute? :external_oauth_audience_list, T::Array.of(T::String).optional
    attribute? :external_oauth_blocked_roles_list, T::Array.of(T::String).optional
    attribute? :external_oauth_jws_keys_url, T::Array.of(T::String).optional
    attribute? :external_oauth_rsa_public_key, T::String.optional
    attribute? :external_oauth_rsa_public_key_2, T::String.optional
    attribute? :external_oauth_scope_delimiter, T::String.optional
    attribute? :external_oauth_scope_mapping_attribute, T::String.optional
  end
end
