# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_oauth_integration_for_partner_applications/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeOauthIntegrationForPartnerApplications
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_oauth_integration_for_partner_applications,
      attributes_class: Snowflake::Types::OauthIntegrationForPartnerApplicationsAttributes,
      outputs: { id: :id },
      map: [:name, :oauth_client],
      map_present: [:blocked_roles_list, :comment, :enabled, :oauth_issue_refresh_tokens, :oauth_redirect_uri, :oauth_refresh_token_validity, :oauth_use_secondary_roles]
  end
  module Snowflake
    include SnowflakeOauthIntegrationForPartnerApplications
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
