# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_database_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeDatabaseRole
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_database_role,
      attributes_class: Snowflake::Types::DatabaseRoleAttributes,
      outputs: { id: :id },
      map: [:database, :name],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeDatabaseRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
