# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_stream_on_external_table/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeStreamOnExternalTable
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_stream_on_external_table,
      attributes_class: Snowflake::Types::StreamOnExternalTableAttributes,
      outputs: { id: :id },
      map: [:database, :external_table, :name, :schema],
      map_present: [:at, :before, :comment, :insert_only],
      map_bool: [:copy_grants]
  end
  module Snowflake
    include SnowflakeStreamOnExternalTable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
