# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class StreamOnExternalTableAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :external_table, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute? :at, T::Array.of(T::Hash).optional
    attribute? :before, T::Array.of(T::Hash).optional
    attribute? :comment, T::String.optional
    attribute? :copy_grants, T::Bool.optional
    attribute? :insert_only, T::String.optional
  end
end
