# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_oauth_integration_for_custom_clients/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeOauthIntegrationForCustomClients
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_oauth_integration_for_custom_clients,
      attributes_class: Snowflake::Types::OauthIntegrationForCustomClientsAttributes,
      outputs: { id: :id },
      map: [:name, :oauth_client_type, :oauth_redirect_uri],
      map_present: [:blocked_roles_list, :comment, :enabled, :network_policy, :oauth_allow_non_tls_redirect_uri, :oauth_client_rsa_public_key, :oauth_client_rsa_public_key_2, :oauth_enforce_pkce, :oauth_issue_refresh_tokens, :oauth_refresh_token_validity, :oauth_use_secondary_roles, :pre_authorized_roles_list]
  end
  module Snowflake
    include SnowflakeOauthIntegrationForCustomClients
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
