# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_password_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakePasswordPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_password_policy,
      attributes_class: Snowflake::Types::PasswordPolicyAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema],
      map_present: [:comment, :history, :lockout_time_mins, :max_age_days, :max_length, :max_retries, :min_age_days, :min_length, :min_lower_case_chars, :min_numeric_chars, :min_special_chars, :min_upper_case_chars],
      map_bool: [:if_not_exists, :or_replace]
  end
  module Snowflake
    include SnowflakePasswordPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
