# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class StreamlitAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :main_file, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute :stage, T::String
    attribute? :comment, T::String.optional
    attribute? :directory_location, T::String.optional
    attribute? :external_access_integrations, T::Array.of(T::String).optional
    attribute? :query_warehouse, T::String.optional
    attribute? :title, T::String.optional
  end
end
