# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_stream_on_view/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeStreamOnView
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_stream_on_view,
      attributes_class: Snowflake::Types::StreamOnViewAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema, :view],
      map_present: [:append_only, :at, :before, :comment, :show_initial_rows],
      map_bool: [:copy_grants]
  end
  module Snowflake
    include SnowflakeStreamOnView
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
