# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class StreamOnViewAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :database, T::String
    attribute :name, T::String
    attribute :schema, T::String
    attribute :view, T::String
    attribute? :append_only, T::String.optional
    attribute? :at, T::Array.of(T::Hash).optional
    attribute? :before, T::Array.of(T::Hash).optional
    attribute? :comment, T::String.optional
    attribute? :copy_grants, T::Bool.optional
    attribute? :show_initial_rows, T::String.optional
  end
end
