# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_storage_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeStorageIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_storage_integration,
      attributes_class: Snowflake::Types::StorageIntegrationAttributes,
      outputs: { id: :id },
      map: [:name, :storage_allowed_locations, :storage_provider],
      map_present: [:azure_tenant_id, :comment, :storage_aws_object_acl, :storage_aws_role_arn, :storage_blocked_locations, :type],
      map_bool: [:enabled]
  end
  module Snowflake
    include SnowflakeStorageIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
