# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_secret_with_client_credentials/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSecretWithClientCredentials
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_secret_with_client_credentials,
      attributes_class: Snowflake::Types::SecretWithClientCredentialsAttributes,
      outputs: { id: :id },
      map: [:api_authentication, :database, :name, :oauth_scopes, :schema],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeSecretWithClientCredentials
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
