# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_shared_database/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeSharedDatabase
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_shared_database,
      attributes_class: Snowflake::Types::SharedDatabaseAttributes,
      outputs: { id: :id },
      map: [:from_share, :name],
      map_present: [:comment]
  end
  module Snowflake
    include SnowflakeSharedDatabase
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
