# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_tag_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeTagAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_tag_association,
      attributes_class: Snowflake::Types::TagAssociationAttributes,
      outputs: { id: :id },
      map: [:object_identifiers, :object_type, :tag_id, :tag_value],
      map_bool: [:skip_validation]
  end
  module Snowflake
    include SnowflakeTagAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
