# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/snowflake_stage/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SnowflakeStage
    include Pangea::Resources::ResourceBuilder

    define_resource :snowflake_stage,
      attributes_class: Snowflake::Types::StageAttributes,
      outputs: { id: :id },
      map: [:database, :name, :schema],
      map_present: [:comment, :copy_options, :credentials, :directory, :encryption, :file_format, :storage_integration, :tag, :url]
  end
  module Snowflake
    include SnowflakeStage
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Snowflake)
