# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class ApiIntegrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :api_allowed_prefixes, T::Array.of(T::String)
    attribute :api_provider, T::String
    attribute :name, T::String
    attribute? :api_aws_role_arn, T::String.optional
    attribute? :api_blocked_prefixes, T::Array.of(T::String).optional
    attribute? :api_key, T::String.optional
    attribute? :azure_ad_application_id, T::String.optional
    attribute? :azure_tenant_id, T::String.optional
    attribute? :comment, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :google_audience, T::String.optional
  end
end
