# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Snowflake::Types
  include Dry.Types()

  class PrimaryConnectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Snowflake::Types

    attribute :name, T::String
    attribute? :comment, T::String.optional
    attribute? :enable_failover_to_accounts, T::Array.of(T::String).optional
  end
end
