# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_authentication_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeAuthenticationPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', name: 'test-value', schema: 'test-value' } }

  describe ':snowflake_authentication_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'test')
        validate_required_attributes(config, [:database, :name, :schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_authentication_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_authentication_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_authentication_policy('test', required_attrs)

        expect(ref.id).to eq("${snowflake_authentication_policy.test.id}")
        expect(ref.describe_output).to eq("${snowflake_authentication_policy.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_authentication_policy.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_authentication_policy.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ authentication_methods: ['test-value'], client_types: ['test-value'], comment: 'test-value', mfa_authentication_methods: ['test-value'], mfa_enrollment: 'test-value', security_integrations: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'full')
        expect(config).to have_key('authentication_methods')
        expect(config).to have_key('client_types')
        expect(config).to have_key('comment')
        expect(config).to have_key('mfa_authentication_methods')
        expect(config).to have_key('mfa_enrollment')
        expect(config).to have_key('security_integrations')
      end
    end

    context 'optional attributes' do
      it 'includes authentication_methods when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('opt', required_attrs.merge(authentication_methods: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'opt')
        expect(config).to have_key('authentication_methods')
      end

      it 'omits authentication_methods when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'minimal')
        expect(config).not_to have_key('authentication_methods')
      end
      it 'includes client_types when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('opt', required_attrs.merge(client_types: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'opt')
        expect(config).to have_key('client_types')
      end

      it 'omits client_types when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'minimal')
        expect(config).not_to have_key('client_types')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes mfa_authentication_methods when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('opt', required_attrs.merge(mfa_authentication_methods: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'opt')
        expect(config).to have_key('mfa_authentication_methods')
      end

      it 'omits mfa_authentication_methods when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'minimal')
        expect(config).not_to have_key('mfa_authentication_methods')
      end
      it 'includes mfa_enrollment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('opt', required_attrs.merge(mfa_enrollment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'opt')
        expect(config).to have_key('mfa_enrollment')
      end

      it 'omits mfa_enrollment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'minimal')
        expect(config).not_to have_key('mfa_enrollment')
      end
      it 'includes security_integrations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('opt', required_attrs.merge(security_integrations: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'opt')
        expect(config).to have_key('security_integrations')
      end

      it 'omits security_integrations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'minimal')
        expect(config).not_to have_key('security_integrations')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_authentication_policy', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_authentication_policy('first', required_attrs)
        synth.snowflake_authentication_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_authentication_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_authentication_policy,
    method: :snowflake_authentication_policy,
    required_attrs: { database: 'test-value', name: 'test-value', schema: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
