# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_object_parameter resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeObjectParameter do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', value: 'test-value' } }

  describe ':snowflake_object_parameter' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'test')
        validate_required_attributes(config, [:key, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_object_parameter('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_object_parameter)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_object_parameter('test', required_attrs)

        expect(ref.id).to eq("${snowflake_object_parameter.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ object_identifier: [{ 'key1' => 'val1' }], object_type: 'test-value', on_account: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_object_parameter', 'full')
        expect(config).to have_key('object_identifier')
        expect(config).to have_key('object_type')
        expect(config).to have_key('on_account')
      end
    end

    context 'optional attributes' do
      it 'includes object_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('opt', required_attrs.merge(object_identifier: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'opt')
        expect(config).to have_key('object_identifier')
      end

      it 'omits object_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'minimal')
        expect(config).not_to have_key('object_identifier')
      end
      it 'includes object_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('opt', required_attrs.merge(object_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'opt')
        expect(config).to have_key('object_type')
      end

      it 'omits object_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'minimal')
        expect(config).not_to have_key('object_type')
      end
      it 'includes on_account when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('opt', required_attrs.merge(on_account: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'opt')
        expect(config).to have_key('on_account')
      end

      it 'omits on_account when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_object_parameter', 'minimal')
        expect(config).not_to have_key('on_account')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts on_account=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(on_account: val)
          synth.snowflake_object_parameter("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_object_parameter', "bool_#{val}")
          expect(config['on_account']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_object_parameter', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_object_parameter('first', required_attrs)
        synth.snowflake_object_parameter('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_object_parameter')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_object_parameter,
    method: :snowflake_object_parameter,
    required_attrs: { key: 'test-value', value: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:on_account]
end
