# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_materialized_view resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeMaterializedView do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', name: 'test-value', schema: 'test-value', statement: 'test-value', warehouse: 'test-value' } }

  describe ':snowflake_materialized_view' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'test')
        validate_required_attributes(config, [:database, :name, :schema, :statement, :warehouse])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_materialized_view('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_materialized_view)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_materialized_view('test', required_attrs)

        expect(ref.id).to eq("${snowflake_materialized_view.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_materialized_view.test.fully_qualified_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_materialized_view', 'test')
        expect(config).not_to have_key('fully_qualified_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', is_secure: true, or_replace: true, tag: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_materialized_view', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('is_secure')
        expect(config).to have_key('or_replace')
        expect(config).to have_key('tag')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes is_secure when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('opt', required_attrs.merge(is_secure: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'opt')
        expect(config).to have_key('is_secure')
      end

      it 'omits is_secure when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'minimal')
        expect(config).not_to have_key('is_secure')
      end
      it 'includes or_replace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('opt', required_attrs.merge(or_replace: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'opt')
        expect(config).to have_key('or_replace')
      end

      it 'omits or_replace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'minimal')
        expect(config).not_to have_key('or_replace')
      end
      it 'includes tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('opt', required_attrs.merge(tag: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'opt')
        expect(config).to have_key('tag')
      end

      it 'omits tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_materialized_view', 'minimal')
        expect(config).not_to have_key('tag')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_secure=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_secure: val)
          synth.snowflake_materialized_view("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_materialized_view', "bool_#{val}")
          expect(config['is_secure']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts or_replace=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(or_replace: val)
          synth.snowflake_materialized_view("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_materialized_view', "bool_#{val}")
          expect(config['or_replace']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_materialized_view', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['statement']).to be_a(String)
        expect(config['warehouse']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_materialized_view('first', required_attrs)
        synth.snowflake_materialized_view('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_materialized_view')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_materialized_view,
    method: :snowflake_materialized_view,
    required_attrs: { database: 'test-value', name: 'test-value', schema: 'test-value', statement: 'test-value', warehouse: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:is_secure, :or_replace]
end
