# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_saml2_integration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeSaml2Integration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', saml2_issuer: 'test-value', saml2_provider: 'test-value', saml2_sso_url: 'test-value', saml2_x509_cert: 'test-value' } }

  describe ':snowflake_saml2_integration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'test')
        validate_required_attributes(config, [:name, :saml2_issuer, :saml2_provider, :saml2_sso_url, :saml2_x509_cert])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_saml2_integration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_saml2_integration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_saml2_integration('test', required_attrs)

        expect(ref.id).to eq("${snowflake_saml2_integration.test.id}")
        expect(ref.describe_output).to eq("${snowflake_saml2_integration.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_saml2_integration.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_saml2_integration.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_email_patterns: ['test-value'], allowed_user_domains: ['test-value'], comment: 'test-value', enabled: 'test-value', saml2_enable_sp_initiated: 'test-value', saml2_force_authn: 'test-value', saml2_post_logout_redirect_url: 'test-value', saml2_requested_nameid_format: 'test-value', saml2_sign_request: 'test-value', saml2_snowflake_acs_url: 'test-value', saml2_snowflake_issuer_url: 'test-value', saml2_sp_initiated_login_page_label: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'full')
        expect(config).to have_key('allowed_email_patterns')
        expect(config).to have_key('allowed_user_domains')
        expect(config).to have_key('comment')
        expect(config).to have_key('enabled')
        expect(config).to have_key('saml2_enable_sp_initiated')
        expect(config).to have_key('saml2_force_authn')
        expect(config).to have_key('saml2_post_logout_redirect_url')
        expect(config).to have_key('saml2_requested_nameid_format')
        expect(config).to have_key('saml2_sign_request')
        expect(config).to have_key('saml2_snowflake_acs_url')
        expect(config).to have_key('saml2_snowflake_issuer_url')
        expect(config).to have_key('saml2_sp_initiated_login_page_label')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_email_patterns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(allowed_email_patterns: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('allowed_email_patterns')
      end

      it 'omits allowed_email_patterns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('allowed_email_patterns')
      end
      it 'includes allowed_user_domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(allowed_user_domains: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('allowed_user_domains')
      end

      it 'omits allowed_user_domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('allowed_user_domains')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(enabled: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes saml2_enable_sp_initiated when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_enable_sp_initiated: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_enable_sp_initiated')
      end

      it 'omits saml2_enable_sp_initiated when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_enable_sp_initiated')
      end
      it 'includes saml2_force_authn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_force_authn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_force_authn')
      end

      it 'omits saml2_force_authn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_force_authn')
      end
      it 'includes saml2_post_logout_redirect_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_post_logout_redirect_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_post_logout_redirect_url')
      end

      it 'omits saml2_post_logout_redirect_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_post_logout_redirect_url')
      end
      it 'includes saml2_requested_nameid_format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_requested_nameid_format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_requested_nameid_format')
      end

      it 'omits saml2_requested_nameid_format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_requested_nameid_format')
      end
      it 'includes saml2_sign_request when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_sign_request: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_sign_request')
      end

      it 'omits saml2_sign_request when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_sign_request')
      end
      it 'includes saml2_snowflake_acs_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_snowflake_acs_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_snowflake_acs_url')
      end

      it 'omits saml2_snowflake_acs_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_snowflake_acs_url')
      end
      it 'includes saml2_snowflake_issuer_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_snowflake_issuer_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_snowflake_issuer_url')
      end

      it 'omits saml2_snowflake_issuer_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_snowflake_issuer_url')
      end
      it 'includes saml2_sp_initiated_login_page_label when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('opt', required_attrs.merge(saml2_sp_initiated_login_page_label: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'opt')
        expect(config).to have_key('saml2_sp_initiated_login_page_label')
      end

      it 'omits saml2_sp_initiated_login_page_label when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'minimal')
        expect(config).not_to have_key('saml2_sp_initiated_login_page_label')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_saml2_integration', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['saml2_issuer']).to be_a(String)
        expect(config['saml2_provider']).to be_a(String)
        expect(config['saml2_sso_url']).to be_a(String)
        expect(config['saml2_x509_cert']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_saml2_integration('first', required_attrs)
        synth.snowflake_saml2_integration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_saml2_integration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_saml2_integration,
    method: :snowflake_saml2_integration,
    required_attrs: { name: 'test-value', saml2_issuer: 'test-value', saml2_provider: 'test-value', saml2_sso_url: 'test-value', saml2_x509_cert: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
