# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_view resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeView do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', name: 'test-value', schema: 'test-value', statement: 'test-value' } }

  describe ':snowflake_view' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_view', 'test')
        validate_required_attributes(config, [:database, :name, :schema, :statement])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_view('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_view)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_view('test', required_attrs)

        expect(ref.id).to eq("${snowflake_view.test.id}")
        expect(ref.describe_output).to eq("${snowflake_view.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_view.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_view.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_view', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ aggregation_policy: [{ 'key1' => 'val1' }], change_tracking: 'test-value', column: [{ 'key1' => 'val1' }], comment: 'test-value', copy_grants: true, data_metric_function: [{ 'key1' => 'val1' }], data_metric_schedule: [{ 'key1' => 'val1' }], is_recursive: 'test-value', is_secure: 'test-value', is_temporary: 'test-value', row_access_policy: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_view', 'full')
        expect(config).to have_key('aggregation_policy')
        expect(config).to have_key('change_tracking')
        expect(config).to have_key('column')
        expect(config).to have_key('comment')
        expect(config).to have_key('copy_grants')
        expect(config).to have_key('data_metric_function')
        expect(config).to have_key('data_metric_schedule')
        expect(config).to have_key('is_recursive')
        expect(config).to have_key('is_secure')
        expect(config).to have_key('is_temporary')
        expect(config).to have_key('row_access_policy')
      end
    end

    context 'optional attributes' do
      it 'includes aggregation_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(aggregation_policy: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('aggregation_policy')
      end

      it 'omits aggregation_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('aggregation_policy')
      end
      it 'includes change_tracking when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(change_tracking: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('change_tracking')
      end

      it 'omits change_tracking when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('change_tracking')
      end
      it 'includes column when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(column: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('column')
      end

      it 'omits column when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('column')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes copy_grants when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(copy_grants: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('copy_grants')
      end

      it 'omits copy_grants when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('copy_grants')
      end
      it 'includes data_metric_function when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(data_metric_function: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('data_metric_function')
      end

      it 'omits data_metric_function when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('data_metric_function')
      end
      it 'includes data_metric_schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(data_metric_schedule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('data_metric_schedule')
      end

      it 'omits data_metric_schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('data_metric_schedule')
      end
      it 'includes is_recursive when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(is_recursive: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('is_recursive')
      end

      it 'omits is_recursive when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('is_recursive')
      end
      it 'includes is_secure when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(is_secure: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('is_secure')
      end

      it 'omits is_secure when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('is_secure')
      end
      it 'includes is_temporary when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(is_temporary: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('is_temporary')
      end

      it 'omits is_temporary when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('is_temporary')
      end
      it 'includes row_access_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('opt', required_attrs.merge(row_access_policy: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'opt')
        expect(config).to have_key('row_access_policy')
      end

      it 'omits row_access_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_view', 'minimal')
        expect(config).not_to have_key('row_access_policy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts copy_grants=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(copy_grants: val)
          synth.snowflake_view("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_view', "bool_#{val}")
          expect(config['copy_grants']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_view', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['statement']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_view('first', required_attrs)
        synth.snowflake_view('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_view')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_view,
    method: :snowflake_view,
    required_attrs: { database: 'test-value', name: 'test-value', schema: 'test-value', statement: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:copy_grants]
end
