# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_external_table resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeExternalTable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { column: [{ 'key1' => 'val1' }], database: 'test-value', file_format: 'test-value', location: 'test-value', name: 'test-value', schema: 'test-value' } }

  describe ':snowflake_external_table' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_external_table', 'test')
        validate_required_attributes(config, [:column, :database, :file_format, :location, :name, :schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_external_table('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_external_table)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_external_table('test', required_attrs)

        expect(ref.id).to eq("${snowflake_external_table.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_external_table.test.fully_qualified_name}")
        expect(ref.owner).to eq("${snowflake_external_table.test.owner}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_table', 'test')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('owner')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_refresh: true, aws_sns_topic: 'test-value', comment: 'test-value', copy_grants: true, partition_by: ['test-value'], pattern: 'test-value', refresh_on_create: true, table_format: 'test-value', tag: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_table', 'full')
        expect(config).to have_key('auto_refresh')
        expect(config).to have_key('aws_sns_topic')
        expect(config).to have_key('comment')
        expect(config).to have_key('copy_grants')
        expect(config).to have_key('partition_by')
        expect(config).to have_key('pattern')
        expect(config).to have_key('refresh_on_create')
        expect(config).to have_key('table_format')
        expect(config).to have_key('tag')
      end
    end

    context 'optional attributes' do
      it 'includes auto_refresh when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(auto_refresh: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('auto_refresh')
      end

      it 'omits auto_refresh when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('auto_refresh')
      end
      it 'includes aws_sns_topic when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(aws_sns_topic: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('aws_sns_topic')
      end

      it 'omits aws_sns_topic when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('aws_sns_topic')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes copy_grants when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(copy_grants: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('copy_grants')
      end

      it 'omits copy_grants when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('copy_grants')
      end
      it 'includes partition_by when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(partition_by: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('partition_by')
      end

      it 'omits partition_by when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('partition_by')
      end
      it 'includes pattern when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(pattern: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('pattern')
      end

      it 'omits pattern when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('pattern')
      end
      it 'includes refresh_on_create when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(refresh_on_create: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('refresh_on_create')
      end

      it 'omits refresh_on_create when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('refresh_on_create')
      end
      it 'includes table_format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(table_format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('table_format')
      end

      it 'omits table_format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('table_format')
      end
      it 'includes tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('opt', required_attrs.merge(tag: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'opt')
        expect(config).to have_key('tag')
      end

      it 'omits tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_table', 'minimal')
        expect(config).not_to have_key('tag')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_refresh=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_refresh: val)
          synth.snowflake_external_table("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_external_table', "bool_#{val}")
          expect(config['auto_refresh']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts copy_grants=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(copy_grants: val)
          synth.snowflake_external_table("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_external_table', "bool_#{val}")
          expect(config['copy_grants']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts refresh_on_create=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(refresh_on_create: val)
          synth.snowflake_external_table("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_external_table', "bool_#{val}")
          expect(config['refresh_on_create']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_table', 'typed')
        expect(config['column']).to be_a(Array)
        expect(config['database']).to be_a(String)
        expect(config['file_format']).to be_a(String)
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_table('first', required_attrs)
        synth.snowflake_external_table('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_external_table')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_external_table,
    method: :snowflake_external_table,
    required_attrs: { column: [{ 'key1' => 'val1' }], database: 'test-value', file_format: 'test-value', location: 'test-value', name: 'test-value', schema: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name, :owner],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:auto_refresh, :copy_grants, :refresh_on_create]
end
