# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_share resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeShare do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':snowflake_share' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_share', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_share('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_share)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_share('test', required_attrs)

        expect(ref.id).to eq("${snowflake_share.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_share.test.fully_qualified_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_share', 'test')
        expect(config).not_to have_key('fully_qualified_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ accounts: ['test-value'], comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_share', 'full')
        expect(config).to have_key('accounts')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes accounts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('opt', required_attrs.merge(accounts: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_share', 'opt')
        expect(config).to have_key('accounts')
      end

      it 'omits accounts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_share', 'minimal')
        expect(config).not_to have_key('accounts')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_share', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_share', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_share', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_share('first', required_attrs)
        synth.snowflake_share('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_share')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_share,
    method: :snowflake_share,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
