# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_table_constraint resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeTableConstraint do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { columns: ['test-value'], name: 'test-value', table_id: 'test-value', type: 'test-value' } }

  describe ':snowflake_table_constraint' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'test')
        validate_required_attributes(config, [:columns, :name, :table_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_table_constraint('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_table_constraint)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_table_constraint('test', required_attrs)

        expect(ref.id).to eq("${snowflake_table_constraint.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', deferrable: true, enable: true, enforced: true, foreign_key_properties: [{ 'key1' => 'val1' }], initially: 'test-value', rely: true, validate: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_table_constraint', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('deferrable')
        expect(config).to have_key('enable')
        expect(config).to have_key('enforced')
        expect(config).to have_key('foreign_key_properties')
        expect(config).to have_key('initially')
        expect(config).to have_key('rely')
        expect(config).to have_key('validate')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes deferrable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(deferrable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('deferrable')
      end

      it 'omits deferrable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('deferrable')
      end
      it 'includes enable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(enable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('enable')
      end

      it 'omits enable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('enable')
      end
      it 'includes enforced when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(enforced: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('enforced')
      end

      it 'omits enforced when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('enforced')
      end
      it 'includes foreign_key_properties when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(foreign_key_properties: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('foreign_key_properties')
      end

      it 'omits foreign_key_properties when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('foreign_key_properties')
      end
      it 'includes initially when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(initially: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('initially')
      end

      it 'omits initially when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('initially')
      end
      it 'includes rely when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(rely: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('rely')
      end

      it 'omits rely when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('rely')
      end
      it 'includes validate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('opt', required_attrs.merge(validate: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'opt')
        expect(config).to have_key('validate')
      end

      it 'omits validate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_table_constraint', 'minimal')
        expect(config).not_to have_key('validate')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts deferrable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(deferrable: val)
          synth.snowflake_table_constraint("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_table_constraint', "bool_#{val}")
          expect(config['deferrable']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable: val)
          synth.snowflake_table_constraint("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_table_constraint', "bool_#{val}")
          expect(config['enable']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enforced=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enforced: val)
          synth.snowflake_table_constraint("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_table_constraint', "bool_#{val}")
          expect(config['enforced']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts rely=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(rely: val)
          synth.snowflake_table_constraint("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_table_constraint', "bool_#{val}")
          expect(config['rely']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts validate=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(validate: val)
          synth.snowflake_table_constraint("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_table_constraint', "bool_#{val}")
          expect(config['validate']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_table_constraint', 'typed')
        expect(config['columns']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['table_id']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_table_constraint('first', required_attrs)
        synth.snowflake_table_constraint('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_table_constraint')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_table_constraint,
    method: :snowflake_table_constraint,
    required_attrs: { columns: ['test-value'], name: 'test-value', table_id: 'test-value', type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:deferrable, :enable, :enforced, :rely, :validate]
end
