# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_stream_on_directory_table resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeStreamOnDirectoryTable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', name: 'test-value', schema: 'test-value', stage: 'test-value' } }

  describe ':snowflake_stream_on_directory_table' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'test')
        validate_required_attributes(config, [:database, :name, :schema, :stage])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_stream_on_directory_table('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_stream_on_directory_table)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_stream_on_directory_table('test', required_attrs)

        expect(ref.id).to eq("${snowflake_stream_on_directory_table.test.id}")
        expect(ref.describe_output).to eq("${snowflake_stream_on_directory_table.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_stream_on_directory_table.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_stream_on_directory_table.test.show_output}")
        expect(ref.stale).to eq("${snowflake_stream_on_directory_table.test.stale}")
        expect(ref.stream_type).to eq("${snowflake_stream_on_directory_table.test.stream_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
        expect(config).not_to have_key('stale')
        expect(config).not_to have_key('stream_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', copy_grants: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('copy_grants')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes copy_grants when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('opt', required_attrs.merge(copy_grants: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'opt')
        expect(config).to have_key('copy_grants')
      end

      it 'omits copy_grants when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'minimal')
        expect(config).not_to have_key('copy_grants')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts copy_grants=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(copy_grants: val)
          synth.snowflake_stream_on_directory_table("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', "bool_#{val}")
          expect(config['copy_grants']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_stream_on_directory_table', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['stage']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_stream_on_directory_table('first', required_attrs)
        synth.snowflake_stream_on_directory_table('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_stream_on_directory_table')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_stream_on_directory_table,
    method: :snowflake_stream_on_directory_table,
    required_attrs: { database: 'test-value', name: 'test-value', schema: 'test-value', stage: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output, :stale, :stream_type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:copy_grants]
end
