# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_api_integration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeApiIntegration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_allowed_prefixes: ['test-value'], api_provider: 'test-value', name: 'test-value' } }

  describe ':snowflake_api_integration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'test')
        validate_required_attributes(config, [:api_allowed_prefixes, :api_provider, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_api_integration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_api_integration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_api_integration('test', required_attrs)

        expect(ref.id).to eq("${snowflake_api_integration.test.id}")
        expect(ref.api_aws_external_id).to eq("${snowflake_api_integration.test.api_aws_external_id}")
        expect(ref.api_aws_iam_user_arn).to eq("${snowflake_api_integration.test.api_aws_iam_user_arn}")
        expect(ref.api_gcp_service_account).to eq("${snowflake_api_integration.test.api_gcp_service_account}")
        expect(ref.azure_consent_url).to eq("${snowflake_api_integration.test.azure_consent_url}")
        expect(ref.azure_multi_tenant_app_name).to eq("${snowflake_api_integration.test.azure_multi_tenant_app_name}")
        expect(ref.created_on).to eq("${snowflake_api_integration.test.created_on}")
        expect(ref.fully_qualified_name).to eq("${snowflake_api_integration.test.fully_qualified_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_api_integration', 'test')
        expect(config).not_to have_key('api_aws_external_id')
        expect(config).not_to have_key('api_aws_iam_user_arn')
        expect(config).not_to have_key('api_gcp_service_account')
        expect(config).not_to have_key('azure_consent_url')
        expect(config).not_to have_key('azure_multi_tenant_app_name')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('fully_qualified_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ api_aws_role_arn: 'test-value', api_blocked_prefixes: ['test-value'], api_key: 'test-value', azure_ad_application_id: 'test-value', azure_tenant_id: 'test-value', comment: 'test-value', enabled: true, google_audience: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_api_integration', 'full')
        expect(config).to have_key('api_aws_role_arn')
        expect(config).to have_key('api_blocked_prefixes')
        expect(config).to have_key('api_key')
        expect(config).to have_key('azure_ad_application_id')
        expect(config).to have_key('azure_tenant_id')
        expect(config).to have_key('comment')
        expect(config).to have_key('enabled')
        expect(config).to have_key('google_audience')
      end
    end

    context 'optional attributes' do
      it 'includes api_aws_role_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(api_aws_role_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('api_aws_role_arn')
      end

      it 'omits api_aws_role_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('api_aws_role_arn')
      end
      it 'includes api_blocked_prefixes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(api_blocked_prefixes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('api_blocked_prefixes')
      end

      it 'omits api_blocked_prefixes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('api_blocked_prefixes')
      end
      it 'includes api_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(api_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('api_key')
      end

      it 'omits api_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('api_key')
      end
      it 'includes azure_ad_application_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(azure_ad_application_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('azure_ad_application_id')
      end

      it 'omits azure_ad_application_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('azure_ad_application_id')
      end
      it 'includes azure_tenant_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(azure_tenant_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('azure_tenant_id')
      end

      it 'omits azure_tenant_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('azure_tenant_id')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes google_audience when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('opt', required_attrs.merge(google_audience: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'opt')
        expect(config).to have_key('google_audience')
      end

      it 'omits google_audience when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_integration', 'minimal')
        expect(config).not_to have_key('google_audience')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:api_key]
        expect(sensitive_fields).to include(:api_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.snowflake_api_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_api_integration', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_api_integration', 'typed')
        expect(config['api_allowed_prefixes']).to be_a(Array)
        expect(config['api_provider']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_integration('first', required_attrs)
        synth.snowflake_api_integration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_api_integration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_api_integration,
    method: :snowflake_api_integration,
    required_attrs: { api_allowed_prefixes: ['test-value'], api_provider: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :api_aws_external_id, :api_aws_iam_user_arn, :api_gcp_service_account, :azure_consent_url, :azure_multi_tenant_app_name, :created_on, :fully_qualified_name],
    sensitive_fields: [:api_key],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
