# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_secondary_database resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeSecondaryDatabase do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { as_replica_of: 'test-value', name: 'test-value' } }

  describe ':snowflake_secondary_database' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_secondary_database', 'test')
        validate_required_attributes(config, [:as_replica_of, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_secondary_database('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_secondary_database)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_secondary_database('test', required_attrs)

        expect(ref.id).to eq("${snowflake_secondary_database.test.id}")
        expect(ref.catalog).to eq("${snowflake_secondary_database.test.catalog}")
        expect(ref.data_retention_time_in_days).to eq("${snowflake_secondary_database.test.data_retention_time_in_days}")
        expect(ref.default_ddl_collation).to eq("${snowflake_secondary_database.test.default_ddl_collation}")
        expect(ref.enable_console_output).to eq("${snowflake_secondary_database.test.enable_console_output}")
        expect(ref.external_volume).to eq("${snowflake_secondary_database.test.external_volume}")
        expect(ref.fully_qualified_name).to eq("${snowflake_secondary_database.test.fully_qualified_name}")
        expect(ref.log_level).to eq("${snowflake_secondary_database.test.log_level}")
        expect(ref.max_data_extension_time_in_days).to eq("${snowflake_secondary_database.test.max_data_extension_time_in_days}")
        expect(ref.quoted_identifiers_ignore_case).to eq("${snowflake_secondary_database.test.quoted_identifiers_ignore_case}")
        expect(ref.replace_invalid_characters).to eq("${snowflake_secondary_database.test.replace_invalid_characters}")
        expect(ref.storage_serialization_policy).to eq("${snowflake_secondary_database.test.storage_serialization_policy}")
        expect(ref.suspend_task_after_num_failures).to eq("${snowflake_secondary_database.test.suspend_task_after_num_failures}")
        expect(ref.task_auto_retry_attempts).to eq("${snowflake_secondary_database.test.task_auto_retry_attempts}")
        expect(ref.trace_level).to eq("${snowflake_secondary_database.test.trace_level}")
        expect(ref.user_task_managed_initial_warehouse_size).to eq("${snowflake_secondary_database.test.user_task_managed_initial_warehouse_size}")
        expect(ref.user_task_minimum_trigger_interval_in_seconds).to eq("${snowflake_secondary_database.test.user_task_minimum_trigger_interval_in_seconds}")
        expect(ref.user_task_timeout_ms).to eq("${snowflake_secondary_database.test.user_task_timeout_ms}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_secondary_database', 'test')
        expect(config).not_to have_key('catalog')
        expect(config).not_to have_key('data_retention_time_in_days')
        expect(config).not_to have_key('default_ddl_collation')
        expect(config).not_to have_key('enable_console_output')
        expect(config).not_to have_key('external_volume')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('log_level')
        expect(config).not_to have_key('max_data_extension_time_in_days')
        expect(config).not_to have_key('quoted_identifiers_ignore_case')
        expect(config).not_to have_key('replace_invalid_characters')
        expect(config).not_to have_key('storage_serialization_policy')
        expect(config).not_to have_key('suspend_task_after_num_failures')
        expect(config).not_to have_key('task_auto_retry_attempts')
        expect(config).not_to have_key('trace_level')
        expect(config).not_to have_key('user_task_managed_initial_warehouse_size')
        expect(config).not_to have_key('user_task_minimum_trigger_interval_in_seconds')
        expect(config).not_to have_key('user_task_timeout_ms')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', is_transient: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_secondary_database', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('is_transient')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_secondary_database', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_secondary_database', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes is_transient when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('opt', required_attrs.merge(is_transient: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_secondary_database', 'opt')
        expect(config).to have_key('is_transient')
      end

      it 'omits is_transient when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_secondary_database', 'minimal')
        expect(config).not_to have_key('is_transient')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_transient=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_transient: val)
          synth.snowflake_secondary_database("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_secondary_database', "bool_#{val}")
          expect(config['is_transient']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_secondary_database', 'typed')
        expect(config['as_replica_of']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secondary_database('first', required_attrs)
        synth.snowflake_secondary_database('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_secondary_database')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_secondary_database,
    method: :snowflake_secondary_database,
    required_attrs: { as_replica_of: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :catalog, :data_retention_time_in_days, :default_ddl_collation, :enable_console_output, :external_volume, :fully_qualified_name, :log_level, :max_data_extension_time_in_days, :quoted_identifiers_ignore_case, :replace_invalid_characters, :storage_serialization_policy, :suspend_task_after_num_failures, :task_auto_retry_attempts, :trace_level, :user_task_managed_initial_warehouse_size, :user_task_minimum_trigger_interval_in_seconds, :user_task_timeout_ms],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:is_transient]
end
