# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_alert resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeAlert do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { action: 'test-value', condition: 'test-value', database: 'test-value', name: 'test-value', schema: 'test-value', warehouse: 'test-value' } }

  describe ':snowflake_alert' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_alert', 'test')
        validate_required_attributes(config, [:action, :condition, :database, :name, :schema, :warehouse])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_alert('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_alert)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_alert('test', required_attrs)

        expect(ref.id).to eq("${snowflake_alert.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_alert.test.fully_qualified_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_alert', 'test')
        expect(config).not_to have_key('fully_qualified_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alert_schedule: [{ 'key1' => 'val1' }], comment: 'test-value', enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_alert', 'full')
        expect(config).to have_key('alert_schedule')
        expect(config).to have_key('comment')
        expect(config).to have_key('enabled')
      end
    end

    context 'optional attributes' do
      it 'includes alert_schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('opt', required_attrs.merge(alert_schedule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_alert', 'opt')
        expect(config).to have_key('alert_schedule')
      end

      it 'omits alert_schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_alert', 'minimal')
        expect(config).not_to have_key('alert_schedule')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_alert', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_alert', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_alert', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_alert', 'minimal')
        expect(config).not_to have_key('enabled')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.snowflake_alert("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_alert', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_alert', 'typed')
        expect(config['action']).to be_a(String)
        expect(config['condition']).to be_a(String)
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['warehouse']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_alert('first', required_attrs)
        synth.snowflake_alert('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_alert')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_alert,
    method: :snowflake_alert,
    required_attrs: { action: 'test-value', condition: 'test-value', database: 'test-value', name: 'test-value', schema: 'test-value', warehouse: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
