# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_grant_application_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeGrantApplicationRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { application_role_name: 'test-value' } }

  describe ':snowflake_grant_application_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'test')
        validate_required_attributes(config, [:application_role_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_grant_application_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_grant_application_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_grant_application_role('test', required_attrs)

        expect(ref.id).to eq("${snowflake_grant_application_role.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ application_name: 'test-value', parent_account_role_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'full')
        expect(config).to have_key('application_name')
        expect(config).to have_key('parent_account_role_name')
      end
    end

    context 'optional attributes' do
      it 'includes application_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('opt', required_attrs.merge(application_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'opt')
        expect(config).to have_key('application_name')
      end

      it 'omits application_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'minimal')
        expect(config).not_to have_key('application_name')
      end
      it 'includes parent_account_role_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('opt', required_attrs.merge(parent_account_role_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'opt')
        expect(config).to have_key('parent_account_role_name')
      end

      it 'omits parent_account_role_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'minimal')
        expect(config).not_to have_key('parent_account_role_name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_grant_application_role', 'typed')
        expect(config['application_role_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_application_role('first', required_attrs)
        synth.snowflake_grant_application_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_grant_application_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_grant_application_role,
    method: :snowflake_grant_application_role,
    required_attrs: { application_role_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
