# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_tag resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeTag do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', name: 'test-value', schema: 'test-value' } }

  describe ':snowflake_tag' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_tag', 'test')
        validate_required_attributes(config, [:database, :name, :schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_tag('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_tag)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_tag('test', required_attrs)

        expect(ref.id).to eq("${snowflake_tag.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_tag.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_tag.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_tag', 'test')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_values: ['test-value'], comment: 'test-value', masking_policies: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_tag', 'full')
        expect(config).to have_key('allowed_values')
        expect(config).to have_key('comment')
        expect(config).to have_key('masking_policies')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('opt', required_attrs.merge(allowed_values: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_tag', 'opt')
        expect(config).to have_key('allowed_values')
      end

      it 'omits allowed_values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_tag', 'minimal')
        expect(config).not_to have_key('allowed_values')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_tag', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_tag', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes masking_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('opt', required_attrs.merge(masking_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_tag', 'opt')
        expect(config).to have_key('masking_policies')
      end

      it 'omits masking_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_tag', 'minimal')
        expect(config).not_to have_key('masking_policies')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_tag', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_tag('first', required_attrs)
        synth.snowflake_tag('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_tag')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_tag,
    method: :snowflake_tag,
    required_attrs: { database: 'test-value', name: 'test-value', schema: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
