# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_secret_with_client_credentials resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeSecretWithClientCredentials do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_authentication: 'test-value', database: 'test-value', name: 'test-value', oauth_scopes: ['test-value'], schema: 'test-value' } }

  describe ':snowflake_secret_with_client_credentials' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_secret_with_client_credentials', 'test')
        validate_required_attributes(config, [:api_authentication, :database, :name, :oauth_scopes, :schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_secret_with_client_credentials('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_secret_with_client_credentials)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_secret_with_client_credentials('test', required_attrs)

        expect(ref.id).to eq("${snowflake_secret_with_client_credentials.test.id}")
        expect(ref.describe_output).to eq("${snowflake_secret_with_client_credentials.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_secret_with_client_credentials.test.fully_qualified_name}")
        expect(ref.secret_type).to eq("${snowflake_secret_with_client_credentials.test.secret_type}")
        expect(ref.show_output).to eq("${snowflake_secret_with_client_credentials.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_secret_with_client_credentials', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('secret_type')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_secret_with_client_credentials', 'full')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_secret_with_client_credentials', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_secret_with_client_credentials', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_secret_with_client_credentials', 'typed')
        expect(config['api_authentication']).to be_a(String)
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['oauth_scopes']).to be_a(Array)
        expect(config['schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_secret_with_client_credentials('first', required_attrs)
        synth.snowflake_secret_with_client_credentials('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_secret_with_client_credentials')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_secret_with_client_credentials,
    method: :snowflake_secret_with_client_credentials,
    required_attrs: { api_authentication: 'test-value', database: 'test-value', name: 'test-value', oauth_scopes: ['test-value'], schema: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :secret_type, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
