# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_cortex_search_service resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeCortexSearchService do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', name: 'test-value', on: 'test-value', query: 'test-value', schema: 'test-value', target_lag: 'test-value', warehouse: 'test-value' } }

  describe ':snowflake_cortex_search_service' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'test')
        validate_required_attributes(config, [:database, :name, :on, :query, :schema, :target_lag, :warehouse])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_cortex_search_service('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_cortex_search_service)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_cortex_search_service('test', required_attrs)

        expect(ref.id).to eq("${snowflake_cortex_search_service.test.id}")
        expect(ref.created_on).to eq("${snowflake_cortex_search_service.test.created_on}")
        expect(ref.fully_qualified_name).to eq("${snowflake_cortex_search_service.test.fully_qualified_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'test')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('fully_qualified_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ attributes: ['test-value'], comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'full')
        expect(config).to have_key('attributes')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes attributes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('opt', required_attrs.merge(attributes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'opt')
        expect(config).to have_key('attributes')
      end

      it 'omits attributes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'minimal')
        expect(config).not_to have_key('attributes')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_cortex_search_service', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['on']).to be_a(String)
        expect(config['query']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['target_lag']).to be_a(String)
        expect(config['warehouse']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_cortex_search_service('first', required_attrs)
        synth.snowflake_cortex_search_service('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_cortex_search_service')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_cortex_search_service,
    method: :snowflake_cortex_search_service,
    required_attrs: { database: 'test-value', name: 'test-value', on: 'test-value', query: 'test-value', schema: 'test-value', target_lag: 'test-value', warehouse: 'test-value' },
    expected_outputs: [:id, :created_on, :fully_qualified_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
