# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_execute resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeExecute do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { execute: 'test-value', revert: 'test-value' } }

  describe ':snowflake_execute' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_execute', 'test')
        validate_required_attributes(config, [:execute, :revert])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_execute('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_execute)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_execute('test', required_attrs)

        expect(ref.id).to eq("${snowflake_execute.test.id}")
        expect(ref.query_results).to eq("${snowflake_execute.test.query_results}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_execute', 'test')
        expect(config).not_to have_key('query_results')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ query: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_execute', 'full')
        expect(config).to have_key('query')
      end
    end

    context 'optional attributes' do
      it 'includes query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('opt', required_attrs.merge(query: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_execute', 'opt')
        expect(config).to have_key('query')
      end

      it 'omits query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_execute', 'minimal')
        expect(config).not_to have_key('query')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_execute', 'typed')
        expect(config['execute']).to be_a(String)
        expect(config['revert']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_execute('first', required_attrs)
        synth.snowflake_execute('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_execute')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_execute,
    method: :snowflake_execute,
    required_attrs: { execute: 'test-value', revert: 'test-value' },
    expected_outputs: [:id, :query_results],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
