# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_grant_privileges_to_share resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeGrantPrivilegesToShare do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { privileges: ['test-value'], to_share: 'test-value' } }

  describe ':snowflake_grant_privileges_to_share' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'test')
        validate_required_attributes(config, [:privileges, :to_share])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_grant_privileges_to_share('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_grant_privileges_to_share)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_grant_privileges_to_share('test', required_attrs)

        expect(ref.id).to eq("${snowflake_grant_privileges_to_share.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ on_all_tables_in_schema: 'test-value', on_database: 'test-value', on_function: 'test-value', on_schema: 'test-value', on_table: 'test-value', on_tag: 'test-value', on_view: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'full')
        expect(config).to have_key('on_all_tables_in_schema')
        expect(config).to have_key('on_database')
        expect(config).to have_key('on_function')
        expect(config).to have_key('on_schema')
        expect(config).to have_key('on_table')
        expect(config).to have_key('on_tag')
        expect(config).to have_key('on_view')
      end
    end

    context 'optional attributes' do
      it 'includes on_all_tables_in_schema when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_all_tables_in_schema: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_all_tables_in_schema')
      end

      it 'omits on_all_tables_in_schema when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_all_tables_in_schema')
      end
      it 'includes on_database when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_database: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_database')
      end

      it 'omits on_database when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_database')
      end
      it 'includes on_function when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_function: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_function')
      end

      it 'omits on_function when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_function')
      end
      it 'includes on_schema when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_schema: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_schema')
      end

      it 'omits on_schema when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_schema')
      end
      it 'includes on_table when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_table: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_table')
      end

      it 'omits on_table when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_table')
      end
      it 'includes on_tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_tag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_tag')
      end

      it 'omits on_tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_tag')
      end
      it 'includes on_view when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('opt', required_attrs.merge(on_view: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'opt')
        expect(config).to have_key('on_view')
      end

      it 'omits on_view when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'minimal')
        expect(config).not_to have_key('on_view')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_share', 'typed')
        expect(config['privileges']).to be_a(Array)
        expect(config['to_share']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_share('first', required_attrs)
        synth.snowflake_grant_privileges_to_share('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_grant_privileges_to_share')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_grant_privileges_to_share,
    method: :snowflake_grant_privileges_to_share,
    required_attrs: { privileges: ['test-value'], to_share: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
