# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_streamlit resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeStreamlit do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', main_file: 'test-value', name: 'test-value', schema: 'test-value', stage: 'test-value' } }

  describe ':snowflake_streamlit' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'test')
        validate_required_attributes(config, [:database, :main_file, :name, :schema, :stage])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_streamlit('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_streamlit)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_streamlit('test', required_attrs)

        expect(ref.id).to eq("${snowflake_streamlit.test.id}")
        expect(ref.describe_output).to eq("${snowflake_streamlit.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_streamlit.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_streamlit.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_streamlit', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', directory_location: 'test-value', external_access_integrations: ['test-value'], query_warehouse: 'test-value', title: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_streamlit', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('directory_location')
        expect(config).to have_key('external_access_integrations')
        expect(config).to have_key('query_warehouse')
        expect(config).to have_key('title')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes directory_location when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('opt', required_attrs.merge(directory_location: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'opt')
        expect(config).to have_key('directory_location')
      end

      it 'omits directory_location when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'minimal')
        expect(config).not_to have_key('directory_location')
      end
      it 'includes external_access_integrations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('opt', required_attrs.merge(external_access_integrations: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'opt')
        expect(config).to have_key('external_access_integrations')
      end

      it 'omits external_access_integrations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'minimal')
        expect(config).not_to have_key('external_access_integrations')
      end
      it 'includes query_warehouse when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('opt', required_attrs.merge(query_warehouse: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'opt')
        expect(config).to have_key('query_warehouse')
      end

      it 'omits query_warehouse when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'minimal')
        expect(config).not_to have_key('query_warehouse')
      end
      it 'includes title when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('opt', required_attrs.merge(title: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'opt')
        expect(config).to have_key('title')
      end

      it 'omits title when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_streamlit', 'minimal')
        expect(config).not_to have_key('title')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_streamlit', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['main_file']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['stage']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_streamlit('first', required_attrs)
        synth.snowflake_streamlit('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_streamlit')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_streamlit,
    method: :snowflake_streamlit,
    required_attrs: { database: 'test-value', main_file: 'test-value', name: 'test-value', schema: 'test-value', stage: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
