# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_file_format resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeFileFormat do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database: 'test-value', format_type: 'test-value', name: 'test-value', schema: 'test-value' } }

  describe ':snowflake_file_format' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_file_format', 'test')
        validate_required_attributes(config, [:database, :format_type, :name, :schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_file_format('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_file_format)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_file_format('test', required_attrs)

        expect(ref.id).to eq("${snowflake_file_format.test.id}")
        expect(ref.binary_format).to eq("${snowflake_file_format.test.binary_format}")
        expect(ref.compression).to eq("${snowflake_file_format.test.compression}")
        expect(ref.date_format).to eq("${snowflake_file_format.test.date_format}")
        expect(ref.encoding).to eq("${snowflake_file_format.test.encoding}")
        expect(ref.escape).to eq("${snowflake_file_format.test.escape}")
        expect(ref.escape_unenclosed_field).to eq("${snowflake_file_format.test.escape_unenclosed_field}")
        expect(ref.field_delimiter).to eq("${snowflake_file_format.test.field_delimiter}")
        expect(ref.field_optionally_enclosed_by).to eq("${snowflake_file_format.test.field_optionally_enclosed_by}")
        expect(ref.fully_qualified_name).to eq("${snowflake_file_format.test.fully_qualified_name}")
        expect(ref.null_if).to eq("${snowflake_file_format.test.null_if}")
        expect(ref.record_delimiter).to eq("${snowflake_file_format.test.record_delimiter}")
        expect(ref.time_format).to eq("${snowflake_file_format.test.time_format}")
        expect(ref.timestamp_format).to eq("${snowflake_file_format.test.timestamp_format}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_file_format', 'test')
        expect(config).not_to have_key('binary_format')
        expect(config).not_to have_key('compression')
        expect(config).not_to have_key('date_format')
        expect(config).not_to have_key('encoding')
        expect(config).not_to have_key('escape')
        expect(config).not_to have_key('escape_unenclosed_field')
        expect(config).not_to have_key('field_delimiter')
        expect(config).not_to have_key('field_optionally_enclosed_by')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('null_if')
        expect(config).not_to have_key('record_delimiter')
        expect(config).not_to have_key('time_format')
        expect(config).not_to have_key('timestamp_format')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_duplicate: true, binary_as_text: true, comment: 'test-value', disable_auto_convert: true, disable_snowflake_data: true, empty_field_as_null: true, enable_octal: true, error_on_column_count_mismatch: true, file_extension: 'test-value', ignore_utf8_errors: true, parse_header: true, preserve_space: true, replace_invalid_characters: true, skip_blank_lines: true, skip_byte_order_mark: true, skip_header: 3.14, strip_null_values: true, strip_outer_array: true, strip_outer_element: true, trim_space: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_file_format', 'full')
        expect(config).to have_key('allow_duplicate')
        expect(config).to have_key('binary_as_text')
        expect(config).to have_key('comment')
        expect(config).to have_key('disable_auto_convert')
        expect(config).to have_key('disable_snowflake_data')
        expect(config).to have_key('empty_field_as_null')
        expect(config).to have_key('enable_octal')
        expect(config).to have_key('error_on_column_count_mismatch')
        expect(config).to have_key('file_extension')
        expect(config).to have_key('ignore_utf8_errors')
        expect(config).to have_key('parse_header')
        expect(config).to have_key('preserve_space')
        expect(config).to have_key('replace_invalid_characters')
        expect(config).to have_key('skip_blank_lines')
        expect(config).to have_key('skip_byte_order_mark')
        expect(config).to have_key('skip_header')
        expect(config).to have_key('strip_null_values')
        expect(config).to have_key('strip_outer_array')
        expect(config).to have_key('strip_outer_element')
        expect(config).to have_key('trim_space')
      end
    end

    context 'optional attributes' do
      it 'includes allow_duplicate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(allow_duplicate: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('allow_duplicate')
      end

      it 'omits allow_duplicate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('allow_duplicate')
      end
      it 'includes binary_as_text when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(binary_as_text: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('binary_as_text')
      end

      it 'omits binary_as_text when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('binary_as_text')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes disable_auto_convert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(disable_auto_convert: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('disable_auto_convert')
      end

      it 'omits disable_auto_convert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('disable_auto_convert')
      end
      it 'includes disable_snowflake_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(disable_snowflake_data: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('disable_snowflake_data')
      end

      it 'omits disable_snowflake_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('disable_snowflake_data')
      end
      it 'includes empty_field_as_null when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(empty_field_as_null: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('empty_field_as_null')
      end

      it 'omits empty_field_as_null when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('empty_field_as_null')
      end
      it 'includes enable_octal when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(enable_octal: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('enable_octal')
      end

      it 'omits enable_octal when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('enable_octal')
      end
      it 'includes error_on_column_count_mismatch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(error_on_column_count_mismatch: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('error_on_column_count_mismatch')
      end

      it 'omits error_on_column_count_mismatch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('error_on_column_count_mismatch')
      end
      it 'includes file_extension when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(file_extension: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('file_extension')
      end

      it 'omits file_extension when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('file_extension')
      end
      it 'includes ignore_utf8_errors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(ignore_utf8_errors: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('ignore_utf8_errors')
      end

      it 'omits ignore_utf8_errors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('ignore_utf8_errors')
      end
      it 'includes parse_header when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(parse_header: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('parse_header')
      end

      it 'omits parse_header when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('parse_header')
      end
      it 'includes preserve_space when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(preserve_space: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('preserve_space')
      end

      it 'omits preserve_space when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('preserve_space')
      end
      it 'includes replace_invalid_characters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(replace_invalid_characters: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('replace_invalid_characters')
      end

      it 'omits replace_invalid_characters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('replace_invalid_characters')
      end
      it 'includes skip_blank_lines when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(skip_blank_lines: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('skip_blank_lines')
      end

      it 'omits skip_blank_lines when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('skip_blank_lines')
      end
      it 'includes skip_byte_order_mark when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(skip_byte_order_mark: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('skip_byte_order_mark')
      end

      it 'omits skip_byte_order_mark when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('skip_byte_order_mark')
      end
      it 'includes skip_header when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(skip_header: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('skip_header')
      end

      it 'omits skip_header when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('skip_header')
      end
      it 'includes strip_null_values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(strip_null_values: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('strip_null_values')
      end

      it 'omits strip_null_values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('strip_null_values')
      end
      it 'includes strip_outer_array when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(strip_outer_array: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('strip_outer_array')
      end

      it 'omits strip_outer_array when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('strip_outer_array')
      end
      it 'includes strip_outer_element when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(strip_outer_element: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('strip_outer_element')
      end

      it 'omits strip_outer_element when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('strip_outer_element')
      end
      it 'includes trim_space when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('opt', required_attrs.merge(trim_space: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'opt')
        expect(config).to have_key('trim_space')
      end

      it 'omits trim_space when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_file_format', 'minimal')
        expect(config).not_to have_key('trim_space')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_duplicate=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_duplicate: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['allow_duplicate']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts binary_as_text=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(binary_as_text: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['binary_as_text']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_auto_convert=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_auto_convert: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['disable_auto_convert']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_snowflake_data=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_snowflake_data: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['disable_snowflake_data']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts empty_field_as_null=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(empty_field_as_null: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['empty_field_as_null']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_octal=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_octal: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['enable_octal']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts error_on_column_count_mismatch=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(error_on_column_count_mismatch: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['error_on_column_count_mismatch']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ignore_utf8_errors=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_utf8_errors: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['ignore_utf8_errors']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts parse_header=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(parse_header: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['parse_header']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts preserve_space=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(preserve_space: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['preserve_space']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts replace_invalid_characters=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(replace_invalid_characters: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['replace_invalid_characters']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_blank_lines=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_blank_lines: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['skip_blank_lines']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_byte_order_mark=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_byte_order_mark: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['skip_byte_order_mark']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts strip_null_values=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(strip_null_values: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['strip_null_values']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts strip_outer_array=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(strip_outer_array: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['strip_outer_array']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts strip_outer_element=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(strip_outer_element: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['strip_outer_element']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts trim_space=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(trim_space: val)
          synth.snowflake_file_format("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_file_format', "bool_#{val}")
          expect(config['trim_space']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_file_format', 'typed')
        expect(config['database']).to be_a(String)
        expect(config['format_type']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_file_format('first', required_attrs)
        synth.snowflake_file_format('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_file_format')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_file_format,
    method: :snowflake_file_format,
    required_attrs: { database: 'test-value', format_type: 'test-value', name: 'test-value', schema: 'test-value' },
    expected_outputs: [:id, :binary_format, :compression, :date_format, :encoding, :escape, :escape_unenclosed_field, :field_delimiter, :field_optionally_enclosed_by, :fully_qualified_name, :null_if, :record_delimiter, :time_format, :timestamp_format],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_duplicate, :binary_as_text, :disable_auto_convert, :disable_snowflake_data, :empty_field_as_null, :enable_octal, :error_on_column_count_mismatch, :ignore_utf8_errors, :parse_header, :preserve_space, :replace_invalid_characters, :skip_blank_lines, :skip_byte_order_mark, :strip_null_values, :strip_outer_array, :strip_outer_element, :trim_space]
end
