# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_warehouse resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeWarehouse do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':snowflake_warehouse' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_warehouse('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_warehouse)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_warehouse('test', required_attrs)

        expect(ref.id).to eq("${snowflake_warehouse.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_warehouse.test.fully_qualified_name}")
        expect(ref.max_concurrency_level).to eq("${snowflake_warehouse.test.max_concurrency_level}")
        expect(ref.parameters).to eq("${snowflake_warehouse.test.parameters}")
        expect(ref.show_output).to eq("${snowflake_warehouse.test.show_output}")
        expect(ref.statement_queued_timeout_in_seconds).to eq("${snowflake_warehouse.test.statement_queued_timeout_in_seconds}")
        expect(ref.statement_timeout_in_seconds).to eq("${snowflake_warehouse.test.statement_timeout_in_seconds}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_warehouse', 'test')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('max_concurrency_level')
        expect(config).not_to have_key('parameters')
        expect(config).not_to have_key('show_output')
        expect(config).not_to have_key('statement_queued_timeout_in_seconds')
        expect(config).not_to have_key('statement_timeout_in_seconds')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_resume: 'test-value', auto_suspend: 3.14, comment: 'test-value', enable_query_acceleration: 'test-value', initially_suspended: true, max_cluster_count: 3.14, min_cluster_count: 3.14, query_acceleration_max_scale_factor: 3.14, resource_monitor: 'test-value', scaling_policy: 'test-value', warehouse_size: 'test-value', warehouse_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_warehouse', 'full')
        expect(config).to have_key('auto_resume')
        expect(config).to have_key('auto_suspend')
        expect(config).to have_key('comment')
        expect(config).to have_key('enable_query_acceleration')
        expect(config).to have_key('initially_suspended')
        expect(config).to have_key('max_cluster_count')
        expect(config).to have_key('min_cluster_count')
        expect(config).to have_key('query_acceleration_max_scale_factor')
        expect(config).to have_key('resource_monitor')
        expect(config).to have_key('scaling_policy')
        expect(config).to have_key('warehouse_size')
        expect(config).to have_key('warehouse_type')
      end
    end

    context 'optional attributes' do
      it 'includes auto_resume when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(auto_resume: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('auto_resume')
      end

      it 'omits auto_resume when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('auto_resume')
      end
      it 'includes auto_suspend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(auto_suspend: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('auto_suspend')
      end

      it 'omits auto_suspend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('auto_suspend')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes enable_query_acceleration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(enable_query_acceleration: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('enable_query_acceleration')
      end

      it 'omits enable_query_acceleration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('enable_query_acceleration')
      end
      it 'includes initially_suspended when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(initially_suspended: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('initially_suspended')
      end

      it 'omits initially_suspended when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('initially_suspended')
      end
      it 'includes max_cluster_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(max_cluster_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('max_cluster_count')
      end

      it 'omits max_cluster_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('max_cluster_count')
      end
      it 'includes min_cluster_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(min_cluster_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('min_cluster_count')
      end

      it 'omits min_cluster_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('min_cluster_count')
      end
      it 'includes query_acceleration_max_scale_factor when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(query_acceleration_max_scale_factor: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('query_acceleration_max_scale_factor')
      end

      it 'omits query_acceleration_max_scale_factor when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('query_acceleration_max_scale_factor')
      end
      it 'includes resource_monitor when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(resource_monitor: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('resource_monitor')
      end

      it 'omits resource_monitor when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('resource_monitor')
      end
      it 'includes scaling_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(scaling_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('scaling_policy')
      end

      it 'omits scaling_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('scaling_policy')
      end
      it 'includes warehouse_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(warehouse_size: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('warehouse_size')
      end

      it 'omits warehouse_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('warehouse_size')
      end
      it 'includes warehouse_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('opt', required_attrs.merge(warehouse_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'opt')
        expect(config).to have_key('warehouse_type')
      end

      it 'omits warehouse_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_warehouse', 'minimal')
        expect(config).not_to have_key('warehouse_type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts initially_suspended=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(initially_suspended: val)
          synth.snowflake_warehouse("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_warehouse', "bool_#{val}")
          expect(config['initially_suspended']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_warehouse', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_warehouse('first', required_attrs)
        synth.snowflake_warehouse('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_warehouse')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_warehouse,
    method: :snowflake_warehouse,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name, :max_concurrency_level, :parameters, :show_output, :statement_queued_timeout_in_seconds, :statement_timeout_in_seconds],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:initially_suspended]
end
