# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_managed_account resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeManagedAccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { admin_name: 'test-value', admin_password: 'test-value', name: 'test-value' } }

  describe ':snowflake_managed_account' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_managed_account', 'test')
        validate_required_attributes(config, [:admin_name, :admin_password, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_managed_account('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_managed_account)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_managed_account('test', required_attrs)

        expect(ref.id).to eq("${snowflake_managed_account.test.id}")
        expect(ref.cloud).to eq("${snowflake_managed_account.test.cloud}")
        expect(ref.created_on).to eq("${snowflake_managed_account.test.created_on}")
        expect(ref.fully_qualified_name).to eq("${snowflake_managed_account.test.fully_qualified_name}")
        expect(ref.locator).to eq("${snowflake_managed_account.test.locator}")
        expect(ref.region).to eq("${snowflake_managed_account.test.region}")
        expect(ref.url).to eq("${snowflake_managed_account.test.url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_managed_account', 'test')
        expect(config).not_to have_key('cloud')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('locator')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_managed_account', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_managed_account', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_managed_account', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_managed_account', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_managed_account', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:admin_password]
        expect(sensitive_fields).to include(:admin_password)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_managed_account', 'typed')
        expect(config['admin_name']).to be_a(String)
        expect(config['admin_password']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_managed_account('first', required_attrs)
        synth.snowflake_managed_account('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_managed_account')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_managed_account,
    method: :snowflake_managed_account,
    required_attrs: { admin_name: 'test-value', admin_password: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :cloud, :created_on, :fully_qualified_name, :locator, :region, :url],
    sensitive_fields: [:admin_password],
    immutable_fields: [],
    boolean_fields: []
end
