# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_external_volume resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeExternalVolume do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', storage_location: [{ 'key1' => 'val1' }] } }

  describe ':snowflake_external_volume' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_external_volume', 'test')
        validate_required_attributes(config, [:name, :storage_location])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_external_volume('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_external_volume)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_external_volume('test', required_attrs)

        expect(ref.id).to eq("${snowflake_external_volume.test.id}")
        expect(ref.describe_output).to eq("${snowflake_external_volume.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_external_volume.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_external_volume.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_volume', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_writes: 'test-value', comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_volume', 'full')
        expect(config).to have_key('allow_writes')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes allow_writes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('opt', required_attrs.merge(allow_writes: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_volume', 'opt')
        expect(config).to have_key('allow_writes')
      end

      it 'omits allow_writes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_volume', 'minimal')
        expect(config).not_to have_key('allow_writes')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_volume', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_volume', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_volume', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['storage_location']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_volume('first', required_attrs)
        synth.snowflake_external_volume('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_external_volume')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_external_volume,
    method: :snowflake_external_volume,
    required_attrs: { name: 'test-value', storage_location: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
