# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_scim_integration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeScimIntegration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enabled: true, name: 'test-value', run_as_role: 'test-value', scim_client: 'test-value' } }

  describe ':snowflake_scim_integration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'test')
        validate_required_attributes(config, [:enabled, :name, :run_as_role, :scim_client])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_scim_integration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_scim_integration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_scim_integration('test', required_attrs)

        expect(ref.id).to eq("${snowflake_scim_integration.test.id}")
        expect(ref.describe_output).to eq("${snowflake_scim_integration.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_scim_integration.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_scim_integration.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_scim_integration', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', network_policy: 'test-value', sync_password: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_scim_integration', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('network_policy')
        expect(config).to have_key('sync_password')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes network_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('opt', required_attrs.merge(network_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'opt')
        expect(config).to have_key('network_policy')
      end

      it 'omits network_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'minimal')
        expect(config).not_to have_key('network_policy')
      end
      it 'includes sync_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('opt', required_attrs.merge(sync_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'opt')
        expect(config).to have_key('sync_password')
      end

      it 'omits sync_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_scim_integration', 'minimal')
        expect(config).not_to have_key('sync_password')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.snowflake_scim_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_scim_integration', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_scim_integration', 'typed')
        expect([true, false]).to include(config['enabled'])
        expect(config['name']).to be_a(String)
        expect(config['run_as_role']).to be_a(String)
        expect(config['scim_client']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_scim_integration('first', required_attrs)
        synth.snowflake_scim_integration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_scim_integration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_scim_integration,
    method: :snowflake_scim_integration,
    required_attrs: { enabled: true, name: 'test-value', run_as_role: 'test-value', scim_client: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
