# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_grant_privileges_to_database_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeGrantPrivilegesToDatabaseRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { database_role_name: 'test-value' } }

  describe ':snowflake_grant_privileges_to_database_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'test')
        validate_required_attributes(config, [:database_role_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_grant_privileges_to_database_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_grant_privileges_to_database_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_grant_privileges_to_database_role('test', required_attrs)

        expect(ref.id).to eq("${snowflake_grant_privileges_to_database_role.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ all_privileges: true, always_apply: true, always_apply_trigger: 'test-value', on_database: 'test-value', on_schema: [{ 'key1' => 'val1' }], on_schema_object: [{ 'key1' => 'val1' }], privileges: ['test-value'], with_grant_option: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'full')
        expect(config).to have_key('all_privileges')
        expect(config).to have_key('always_apply')
        expect(config).to have_key('always_apply_trigger')
        expect(config).to have_key('on_database')
        expect(config).to have_key('on_schema')
        expect(config).to have_key('on_schema_object')
        expect(config).to have_key('privileges')
        expect(config).to have_key('with_grant_option')
      end
    end

    context 'optional attributes' do
      it 'includes all_privileges when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(all_privileges: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('all_privileges')
      end

      it 'omits all_privileges when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('all_privileges')
      end
      it 'includes always_apply when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(always_apply: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('always_apply')
      end

      it 'omits always_apply when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('always_apply')
      end
      it 'includes always_apply_trigger when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(always_apply_trigger: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('always_apply_trigger')
      end

      it 'omits always_apply_trigger when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('always_apply_trigger')
      end
      it 'includes on_database when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(on_database: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('on_database')
      end

      it 'omits on_database when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('on_database')
      end
      it 'includes on_schema when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(on_schema: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('on_schema')
      end

      it 'omits on_schema when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('on_schema')
      end
      it 'includes on_schema_object when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(on_schema_object: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('on_schema_object')
      end

      it 'omits on_schema_object when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('on_schema_object')
      end
      it 'includes privileges when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(privileges: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('privileges')
      end

      it 'omits privileges when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('privileges')
      end
      it 'includes with_grant_option when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('opt', required_attrs.merge(with_grant_option: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'opt')
        expect(config).to have_key('with_grant_option')
      end

      it 'omits with_grant_option when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'minimal')
        expect(config).not_to have_key('with_grant_option')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts all_privileges=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(all_privileges: val)
          synth.snowflake_grant_privileges_to_database_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', "bool_#{val}")
          expect(config['all_privileges']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts always_apply=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(always_apply: val)
          synth.snowflake_grant_privileges_to_database_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', "bool_#{val}")
          expect(config['always_apply']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts with_grant_option=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(with_grant_option: val)
          synth.snowflake_grant_privileges_to_database_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', "bool_#{val}")
          expect(config['with_grant_option']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_grant_privileges_to_database_role', 'typed')
        expect(config['database_role_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_grant_privileges_to_database_role('first', required_attrs)
        synth.snowflake_grant_privileges_to_database_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_grant_privileges_to_database_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_grant_privileges_to_database_role,
    method: :snowflake_grant_privileges_to_database_role,
    required_attrs: { database_role_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:all_privileges, :always_apply, :with_grant_option]
end
