# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_api_authentication_integration_with_authorization_code_grant resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeApiAuthenticationIntegrationWithAuthorizationCodeGrant do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enabled: true, name: 'test-value', oauth_client_id: 'test-value', oauth_client_secret: 'test-value' } }

  describe ':snowflake_api_authentication_integration_with_authorization_code_grant' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'test')
        validate_required_attributes(config, [:enabled, :name, :oauth_client_id, :oauth_client_secret])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_api_authentication_integration_with_authorization_code_grant('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_api_authentication_integration_with_authorization_code_grant)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_api_authentication_integration_with_authorization_code_grant('test', required_attrs)

        expect(ref.id).to eq("${snowflake_api_authentication_integration_with_authorization_code_grant.test.id}")
        expect(ref.describe_output).to eq("${snowflake_api_authentication_integration_with_authorization_code_grant.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_api_authentication_integration_with_authorization_code_grant.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_api_authentication_integration_with_authorization_code_grant.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', oauth_access_token_validity: 3.14, oauth_allowed_scopes: ['test-value'], oauth_authorization_endpoint: 'test-value', oauth_client_auth_method: 'test-value', oauth_refresh_token_validity: 3.14, oauth_token_endpoint: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('oauth_access_token_validity')
        expect(config).to have_key('oauth_allowed_scopes')
        expect(config).to have_key('oauth_authorization_endpoint')
        expect(config).to have_key('oauth_client_auth_method')
        expect(config).to have_key('oauth_refresh_token_validity')
        expect(config).to have_key('oauth_token_endpoint')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes oauth_access_token_validity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(oauth_access_token_validity: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('oauth_access_token_validity')
      end

      it 'omits oauth_access_token_validity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('oauth_access_token_validity')
      end
      it 'includes oauth_allowed_scopes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(oauth_allowed_scopes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('oauth_allowed_scopes')
      end

      it 'omits oauth_allowed_scopes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('oauth_allowed_scopes')
      end
      it 'includes oauth_authorization_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(oauth_authorization_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('oauth_authorization_endpoint')
      end

      it 'omits oauth_authorization_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('oauth_authorization_endpoint')
      end
      it 'includes oauth_client_auth_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(oauth_client_auth_method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('oauth_client_auth_method')
      end

      it 'omits oauth_client_auth_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('oauth_client_auth_method')
      end
      it 'includes oauth_refresh_token_validity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(oauth_refresh_token_validity: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('oauth_refresh_token_validity')
      end

      it 'omits oauth_refresh_token_validity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('oauth_refresh_token_validity')
      end
      it 'includes oauth_token_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('opt', required_attrs.merge(oauth_token_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'opt')
        expect(config).to have_key('oauth_token_endpoint')
      end

      it 'omits oauth_token_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'minimal')
        expect(config).not_to have_key('oauth_token_endpoint')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.snowflake_api_authentication_integration_with_authorization_code_grant("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_api_authentication_integration_with_authorization_code_grant', 'typed')
        expect([true, false]).to include(config['enabled'])
        expect(config['name']).to be_a(String)
        expect(config['oauth_client_id']).to be_a(String)
        expect(config['oauth_client_secret']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('first', required_attrs)
        synth.snowflake_api_authentication_integration_with_authorization_code_grant('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_api_authentication_integration_with_authorization_code_grant')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_api_authentication_integration_with_authorization_code_grant,
    method: :snowflake_api_authentication_integration_with_authorization_code_grant,
    required_attrs: { enabled: true, name: 'test-value', oauth_client_id: 'test-value', oauth_client_secret: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
