# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_network_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeNetworkPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':snowflake_network_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_network_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_network_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_network_policy('test', required_attrs)

        expect(ref.id).to eq("${snowflake_network_policy.test.id}")
        expect(ref.describe_output).to eq("${snowflake_network_policy.test.describe_output}")
        expect(ref.fully_qualified_name).to eq("${snowflake_network_policy.test.fully_qualified_name}")
        expect(ref.show_output).to eq("${snowflake_network_policy.test.show_output}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_network_policy', 'test')
        expect(config).not_to have_key('describe_output')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('show_output')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_ip_list: ['test-value'], allowed_network_rule_list: ['test-value'], blocked_ip_list: ['test-value'], blocked_network_rule_list: ['test-value'], comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_network_policy', 'full')
        expect(config).to have_key('allowed_ip_list')
        expect(config).to have_key('allowed_network_rule_list')
        expect(config).to have_key('blocked_ip_list')
        expect(config).to have_key('blocked_network_rule_list')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_ip_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('opt', required_attrs.merge(allowed_ip_list: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'opt')
        expect(config).to have_key('allowed_ip_list')
      end

      it 'omits allowed_ip_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'minimal')
        expect(config).not_to have_key('allowed_ip_list')
      end
      it 'includes allowed_network_rule_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('opt', required_attrs.merge(allowed_network_rule_list: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'opt')
        expect(config).to have_key('allowed_network_rule_list')
      end

      it 'omits allowed_network_rule_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'minimal')
        expect(config).not_to have_key('allowed_network_rule_list')
      end
      it 'includes blocked_ip_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('opt', required_attrs.merge(blocked_ip_list: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'opt')
        expect(config).to have_key('blocked_ip_list')
      end

      it 'omits blocked_ip_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'minimal')
        expect(config).not_to have_key('blocked_ip_list')
      end
      it 'includes blocked_network_rule_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('opt', required_attrs.merge(blocked_network_rule_list: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'opt')
        expect(config).to have_key('blocked_network_rule_list')
      end

      it 'omits blocked_network_rule_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'minimal')
        expect(config).not_to have_key('blocked_network_rule_list')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_network_policy', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_network_policy', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_network_policy('first', required_attrs)
        synth.snowflake_network_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_network_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_network_policy,
    method: :snowflake_network_policy,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :describe_output, :fully_qualified_name, :show_output],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
