# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_user_public_keys resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeUserPublicKeys do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':snowflake_user_public_keys' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_user_public_keys('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_user_public_keys)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_user_public_keys('test', required_attrs)

        expect(ref.id).to eq("${snowflake_user_public_keys.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ rsa_public_key: 'test-value', rsa_public_key_2: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'full')
        expect(config).to have_key('rsa_public_key')
        expect(config).to have_key('rsa_public_key_2')
      end
    end

    context 'optional attributes' do
      it 'includes rsa_public_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('opt', required_attrs.merge(rsa_public_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'opt')
        expect(config).to have_key('rsa_public_key')
      end

      it 'omits rsa_public_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'minimal')
        expect(config).not_to have_key('rsa_public_key')
      end
      it 'includes rsa_public_key_2 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('opt', required_attrs.merge(rsa_public_key_2: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'opt')
        expect(config).to have_key('rsa_public_key_2')
      end

      it 'omits rsa_public_key_2 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'minimal')
        expect(config).not_to have_key('rsa_public_key_2')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_user_public_keys', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_user_public_keys('first', required_attrs)
        synth.snowflake_user_public_keys('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_user_public_keys')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_user_public_keys,
    method: :snowflake_user_public_keys,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
