# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_external_function resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakeExternalFunction do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_integration: 'test-value', database: 'test-value', name: 'test-value', return_behavior: 'test-value', return_type: 'test-value', schema: 'test-value', url_of_proxy_and_resource: 'test-value' } }

  describe ':snowflake_external_function' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_external_function', 'test')
        validate_required_attributes(config, [:api_integration, :database, :name, :return_behavior, :return_type, :schema, :url_of_proxy_and_resource])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_external_function('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_external_function)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_external_function('test', required_attrs)

        expect(ref.id).to eq("${snowflake_external_function.test.id}")
        expect(ref.created_on).to eq("${snowflake_external_function.test.created_on}")
        expect(ref.fully_qualified_name).to eq("${snowflake_external_function.test.fully_qualified_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_function', 'test')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('fully_qualified_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ arg: [{ 'key1' => 'val1' }], comment: 'test-value', compression: 'test-value', context_headers: ['test-value'], header: [{ 'key1' => 'val1' }], max_batch_rows: 3.14, null_input_behavior: 'test-value', request_translator: 'test-value', response_translator: 'test-value', return_null_allowed: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_function', 'full')
        expect(config).to have_key('arg')
        expect(config).to have_key('comment')
        expect(config).to have_key('compression')
        expect(config).to have_key('context_headers')
        expect(config).to have_key('header')
        expect(config).to have_key('max_batch_rows')
        expect(config).to have_key('null_input_behavior')
        expect(config).to have_key('request_translator')
        expect(config).to have_key('response_translator')
        expect(config).to have_key('return_null_allowed')
      end
    end

    context 'optional attributes' do
      it 'includes arg when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(arg: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('arg')
      end

      it 'omits arg when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('arg')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes compression when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(compression: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('compression')
      end

      it 'omits compression when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('compression')
      end
      it 'includes context_headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(context_headers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('context_headers')
      end

      it 'omits context_headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('context_headers')
      end
      it 'includes header when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(header: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('header')
      end

      it 'omits header when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('header')
      end
      it 'includes max_batch_rows when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(max_batch_rows: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('max_batch_rows')
      end

      it 'omits max_batch_rows when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('max_batch_rows')
      end
      it 'includes null_input_behavior when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(null_input_behavior: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('null_input_behavior')
      end

      it 'omits null_input_behavior when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('null_input_behavior')
      end
      it 'includes request_translator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(request_translator: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('request_translator')
      end

      it 'omits request_translator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('request_translator')
      end
      it 'includes response_translator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(response_translator: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('response_translator')
      end

      it 'omits response_translator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('response_translator')
      end
      it 'includes return_null_allowed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('opt', required_attrs.merge(return_null_allowed: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'opt')
        expect(config).to have_key('return_null_allowed')
      end

      it 'omits return_null_allowed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_external_function', 'minimal')
        expect(config).not_to have_key('return_null_allowed')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts return_null_allowed=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(return_null_allowed: val)
          synth.snowflake_external_function("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_external_function', "bool_#{val}")
          expect(config['return_null_allowed']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_external_function', 'typed')
        expect(config['api_integration']).to be_a(String)
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['return_behavior']).to be_a(String)
        expect(config['return_type']).to be_a(String)
        expect(config['schema']).to be_a(String)
        expect(config['url_of_proxy_and_resource']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_external_function('first', required_attrs)
        synth.snowflake_external_function('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_external_function')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_external_function,
    method: :snowflake_external_function,
    required_attrs: { api_integration: 'test-value', database: 'test-value', name: 'test-value', return_behavior: 'test-value', return_type: 'test-value', schema: 'test-value', url_of_proxy_and_resource: 'test-value' },
    expected_outputs: [:id, :created_on, :fully_qualified_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:return_null_allowed]
end
