# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a snowflake_pipe resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SnowflakePipe do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { copy_statement: 'test-value', database: 'test-value', name: 'test-value', schema: 'test-value' } }

  describe ':snowflake_pipe' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'snowflake_pipe', 'test')
        validate_required_attributes(config, [:copy_statement, :database, :name, :schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_pipe('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:snowflake_pipe)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.snowflake_pipe('test', required_attrs)

        expect(ref.id).to eq("${snowflake_pipe.test.id}")
        expect(ref.fully_qualified_name).to eq("${snowflake_pipe.test.fully_qualified_name}")
        expect(ref.notification_channel).to eq("${snowflake_pipe.test.notification_channel}")
        expect(ref.owner).to eq("${snowflake_pipe.test.owner}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_pipe', 'test')
        expect(config).not_to have_key('fully_qualified_name')
        expect(config).not_to have_key('notification_channel')
        expect(config).not_to have_key('owner')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_ingest: true, aws_sns_topic_arn: 'test-value', comment: 'test-value', error_integration: 'test-value', integration: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_pipe', 'full')
        expect(config).to have_key('auto_ingest')
        expect(config).to have_key('aws_sns_topic_arn')
        expect(config).to have_key('comment')
        expect(config).to have_key('error_integration')
        expect(config).to have_key('integration')
      end
    end

    context 'optional attributes' do
      it 'includes auto_ingest when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('opt', required_attrs.merge(auto_ingest: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'opt')
        expect(config).to have_key('auto_ingest')
      end

      it 'omits auto_ingest when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'minimal')
        expect(config).not_to have_key('auto_ingest')
      end
      it 'includes aws_sns_topic_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('opt', required_attrs.merge(aws_sns_topic_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'opt')
        expect(config).to have_key('aws_sns_topic_arn')
      end

      it 'omits aws_sns_topic_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'minimal')
        expect(config).not_to have_key('aws_sns_topic_arn')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes error_integration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('opt', required_attrs.merge(error_integration: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'opt')
        expect(config).to have_key('error_integration')
      end

      it 'omits error_integration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'minimal')
        expect(config).not_to have_key('error_integration')
      end
      it 'includes integration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('opt', required_attrs.merge(integration: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'opt')
        expect(config).to have_key('integration')
      end

      it 'omits integration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'snowflake_pipe', 'minimal')
        expect(config).not_to have_key('integration')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_ingest=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_ingest: val)
          synth.snowflake_pipe("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'snowflake_pipe', "bool_#{val}")
          expect(config['auto_ingest']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'snowflake_pipe', 'typed')
        expect(config['copy_statement']).to be_a(String)
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.snowflake_pipe('first', required_attrs)
        synth.snowflake_pipe('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'snowflake_pipe')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :snowflake_pipe,
    method: :snowflake_pipe,
    required_attrs: { copy_statement: 'test-value', database: 'test-value', name: 'test-value', schema: 'test-value' },
    expected_outputs: [:id, :fully_qualified_name, :notification_channel, :owner],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:auto_ingest]
end
